#pragma once

#define CONFIG_GRID_CELL_SIZE (100)

#define CONFIG_DIRECTION_COUNT_NOT_MIRRORED (5)

#define CONFIG_ANIMATION_DIVISOR (4)

#define CONFIG_ANIMATION_DECAY_DIVISOR (50 * CONFIG_ANIMATION_DIVISOR)

#define CONFIG_UNIT_ALIGNMENT_DEADZONE (3)

#define CONFIG_UNIT_PATHING_TIMEOUT_CYCLES (20)

#define CONFIG_POINT_GOAL_CLOSE_ENOUGH_MAG (10)

#define CONFIG_UNIT_DIRECTION_TIMER_EXPIRE (10)

#define CONFIG_UNITS_STRESSOR_DEADZONE (10)

#define CONFIG_UNIT_VELOCITY_DEADZONE (70)

#define CONFIG_UNIT_COHESION_COUNT (10)

#define CONFIG_OVERVIEW_SCROLL_SPEED (15)

#define CONFIG_OVERVIEW_SELECTION_BOX_MIN_SIZE (200)

#define CONFIG_VIDEO_TOP_LEFT_BORDER_OFFSET_UNITS (-600) // Make big enough to enscapsulate largest building on the render screen.

#define CONFIG_VIDEO_TOP_LEFT_BORDER_OFFSET_TERRAIN (-75)

#define CONFIG_FIELD_MAX_PATHING_TRIES (1000)

#define CONFIG_UNITS_COHESE_DIVISOR (64)

#define CONFIG_UNITS_SEPARATION_DIVISOR (16)

#define CONFIG_UNITS_ALIGN_DIVISOR (32)

#define CONFIG_UNIT_SWORD_LENGTH (300)

#define CONFIG_UNITS_REPATH_SLICE_SIZE (10)
