#pragma once

#include "Type.h"
#include "Action.h"

#include <stdint.h>
#include <stdio.h>
#include <stdbool.h>

typedef struct
{
    int32_t id;
    int32_t data_offset;
    int32_t size;
}
File;

void File_Print(const File);

File File_Load(FILE* const);

#define FILE_NONE (-1)

#define FILE_PRIO_TERRAIN (1)
#define FILE_PRIO_SHADOW (2)
#define FILE_PRIO_DECAY (3)
#define FILE_PRIO_BUILDING (4)
#define FILE_PRIO_UNIT (5)
#define FILE_PRIO_HIGHEST (255)

#define FILE_DIMENSIONS_1X1 {1,1}
#define FILE_DIMENSIONS_2X1 {2,1}
#define FILE_DIMENSIONS_2X2 {2,2}
#define FILE_DIMENSIONS_3X3 {3,3}
#define FILE_DIMENSIONS_4X4 {4,4}
#define FILE_DIMENSIONS_5X5 {5,5}
#define FILE_DIMENSIONS_6X6 {6,6}

// For more details about X-Macros: https://en.wikipedia.org/wiki/X_Macro
// This X-Macro is used in: Interfac.[ch]. Graphics.[ch], Terrain.[ch], Registrar.c
// To get an idea of how the X-Macro expands in Graphics.c, for instance, run: gcc -E Graphics.c | clang-format
//  ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
//                                                             |           |                   |                  | W  |                       |       |         |        |         |  S  |  M  |  E  |  I  |                    |                 | D  | M
//                                                             |           |                   |                  | A  |                       |       |         |        |         |  I  |  U  |  X  |  N  |                    |                 | E  | I
//                                                             |           |                   |                  | K  |                       |       |         |        |         |  N  |  L  |  P  |  A  |                    |                 | T  | D
//                                                             |           |                   |                  | A  |                       |       |         |        |         |  G  |  T  |  I  |  N  |                    |                 | A  | D
//                                                             |           |                   |                  | B  |                       |       |         |        |         |  L  |  I  |  R  |  I  |                    |                 | I  | E
//                                                             |           |                   |                  | L  |                       |       |         |        |         |  E  |  S  |  E  |  M  |                    |                 | L  | D
//                                                             |           |                   |                  | E  |                       |       |         |        |         |  F  |  T  |     |  A  |                    |                 |    |
//                                                             |           |                   |                  |    |                       |       |         |        |         |  R  |  A  |     |  T  |                    |                 |    |
//                                                             |           |                   |                  |    |                       |       |         |        |         |  A  |  T  |     |  E  |                    |                 |    |
//                                                             |           |                   |                  |    |                       | MAX   |         |        |         |  M  |  E  |     |     |                    |                 |    |
//  NAME                                                       | FILE      | UPGRADE           | PRIO             |    | TYPE                  | SPEED | HEALTH  | ATTACK | WIDTH   |  E  |     |     |     | DIMENSIONS         | ACTION          |    |
//  ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#define FILE_X_INTERFAC \
    FILE_X(FILE_INTERFAC_NONE,                                   FILE_NONE, FILE_GRAPHICS_NONE, FILE_PRIO_HIGHEST,  (0), TYPE_NONE,                (0),      (0),    (0),    (0),     (0),  (0),  (0),  (0), FILE_DIMENSIONS_1X1, ACTION_NONE,      (1), (0)) \
    FILE_X(FILE_INTERFAC_BUILDING_ICONS,                              (66), FILE_GRAPHICS_NONE, FILE_PRIO_HIGHEST,  (0), TYPE_NONE,                (0),      (0),    (0),    (0),     (0),  (0),  (0),  (0), FILE_DIMENSIONS_1X1, ACTION_NONE,      (1), (0)) \
    FILE_X(FILE_INTERFAC_COMMAND_ICONS,                               (78), FILE_GRAPHICS_NONE, FILE_PRIO_HIGHEST,  (0), TYPE_NONE,                (0),      (0),    (0),    (0),     (0),  (0),  (0),  (0), FILE_DIMENSIONS_1X1, ACTION_NONE,      (1), (0)) \
    FILE_X(FILE_INTERFAC_TECH_ICONS,                                  (83), FILE_GRAPHICS_NONE, FILE_PRIO_HIGHEST,  (0), TYPE_NONE,                (0),      (0),    (0),    (0),     (0),  (0),  (0),  (0), FILE_DIMENSIONS_1X1, ACTION_NONE,      (1), (0)) \
    FILE_X(FILE_INTERFAC_UNIT_ICONS,                                  (84), FILE_GRAPHICS_NONE, FILE_PRIO_HIGHEST,  (0), TYPE_NONE,                (0),      (0),    (0),    (0),     (0),  (0),  (0),  (0), FILE_DIMENSIONS_1X1, ACTION_NONE,      (1), (0)) \
    FILE_X(FILE_INTERFAC_HUD_0,                                      (158), FILE_GRAPHICS_NONE, FILE_PRIO_HIGHEST,  (0), TYPE_NONE,                (0),      (0),    (0),    (0),     (0),  (0),  (0),  (0), FILE_DIMENSIONS_1X1, ACTION_NONE,      (1), (0))
#define FILE_X_TERRAIN \
    FILE_X(FILE_TERRAIN_NONE,                                    FILE_NONE, FILE_GRAPHICS_NONE, FILE_PRIO_HIGHEST,  (1), TYPE_NONE,                (0),      (0),    (0),    (0),     (0),  (0),  (0),  (0), FILE_DIMENSIONS_1X1, ACTION_NONE,      (1), (0)) \
    FILE_X(FILE_DIRT,                                                  (0), FILE_GRAPHICS_NONE, FILE_PRIO_TERRAIN,  (1), TYPE_NONE,                (0),      (0),    (0),    (0),     (0),  (0),  (0),  (0), FILE_DIMENSIONS_1X1, ACTION_NONE,      (1), (0)) \
    FILE_X(FILE_GRASS,                                                 (1), FILE_GRAPHICS_NONE, FILE_PRIO_TERRAIN,  (1), TYPE_NONE,                (0),      (0),    (0),    (0),     (0),  (0),  (0),  (0), FILE_DIMENSIONS_1X1, ACTION_NONE,      (1), (0)) \
    FILE_X(FILE_WATER,                                                 (2), FILE_GRAPHICS_NONE, FILE_PRIO_TERRAIN,  (0), TYPE_NONE,                (0),      (0),    (0),    (0),     (0),  (0),  (0),  (0), FILE_DIMENSIONS_1X1, ACTION_NONE,      (1), (0)) \
    FILE_X(FILE_FARM,                                                  (3), FILE_GRAPHICS_NONE, FILE_PRIO_TERRAIN,  (1), TYPE_NONE,                (0),      (0),    (0),    (0),     (0),  (0),  (0),  (0), FILE_DIMENSIONS_1X1, ACTION_NONE,      (1), (0))
#define FILE_X_GRAPHICS \
    FILE_X(FILE_GRAPHICS_NONE,                                   FILE_NONE, FILE_GRAPHICS_NONE, FILE_PRIO_HIGHEST,  (1), TYPE_NONE,                (0),      (0),    (0),    (0),     (0),  (0),  (0),  (0), FILE_DIMENSIONS_1X1, ACTION_NONE,      (1), (0)) \
    FILE_X(FILE_SMALLER_EXPLOSION_SMOKE,                              (21), FILE_GRAPHICS_NONE, FILE_PRIO_BUILDING, (1), TYPE_SMOKE,               (0),      (0),    (0),    (0),     (0),  (0),  (1),  (1), FILE_DIMENSIONS_1X1, ACTION_NONE,      (1), (0)) \
    FILE_X(FILE_AGE_2_NORTH_EUROPE_BARRACKS,                          (38), FILE_GRAPHICS_NONE, FILE_PRIO_BUILDING, (0), TYPE_BARRACKS,            (0),    (100),    (0),    (0),     (1),  (0),  (0),  (1), FILE_DIMENSIONS_3X3, ACTION_UNIT_TECH, (0), (0)) \
    FILE_X(FILE_AGE_2_ASIA_BARRACKS,                                  (39), FILE_GRAPHICS_NONE, FILE_PRIO_BUILDING, (0), TYPE_BARRACKS,            (0),    (100),    (0),    (0),     (1),  (0),  (0),  (1), FILE_DIMENSIONS_3X3, ACTION_UNIT_TECH, (0), (0)) \
    FILE_X(FILE_AGE_2_ARAB_BARRACKS,                                  (40), FILE_GRAPHICS_NONE, FILE_PRIO_BUILDING, (0), TYPE_BARRACKS,            (0),    (100),    (0),    (0),     (1),  (0),  (0),  (1), FILE_DIMENSIONS_3X3, ACTION_UNIT_TECH, (0), (0)) \
    FILE_X(FILE_AGE_2_WEST_EUROPE_BARRACKS,                           (41), FILE_GRAPHICS_NONE, FILE_PRIO_BUILDING, (0), TYPE_BARRACKS,            (0),    (100),    (0),    (0),     (1),  (0),  (0),  (1), FILE_DIMENSIONS_3X3, ACTION_UNIT_TECH, (0), (0)) \
    FILE_X(FILE_AGE_3_NORTH_EUROPE_BARRACKS,                          (42), FILE_GRAPHICS_NONE, FILE_PRIO_BUILDING, (0), TYPE_BARRACKS,            (0),    (100),    (0),    (0),     (1),  (0),  (0),  (1), FILE_DIMENSIONS_3X3, ACTION_UNIT_TECH, (0), (0)) \
    FILE_X(FILE_AGE_3_ASIA_BARRACKS,                                  (43), FILE_GRAPHICS_NONE, FILE_PRIO_BUILDING, (0), TYPE_BARRACKS,            (0),    (100),    (0),    (0),     (1),  (0),  (0),  (1), FILE_DIMENSIONS_3X3, ACTION_UNIT_TECH, (0), (0)) \
    FILE_X(FILE_AGE_3_ARAB_BARRACKS,                                  (44), FILE_GRAPHICS_NONE, FILE_PRIO_BUILDING, (0), TYPE_BARRACKS,            (0),    (100),    (0),    (0),     (1),  (0),  (0),  (1), FILE_DIMENSIONS_3X3, ACTION_UNIT_TECH, (0), (0)) \
    FILE_X(FILE_AGE_3_WEST_EUROPE_BARRACKS,                           (45), FILE_GRAPHICS_NONE, FILE_PRIO_BUILDING, (0), TYPE_BARRACKS,            (0),    (100),    (0),    (0),     (1),  (0),  (0),  (1), FILE_DIMENSIONS_3X3, ACTION_UNIT_TECH, (0), (0)) \
    FILE_X(FILE_NORTH_EUROPE_CASTLE_SHADOW,                           (96), FILE_GRAPHICS_NONE, FILE_PRIO_SHADOW,   (1), TYPE_SHADOW,              (0),      (0),    (0),    (0),     (1),  (0),  (0),  (1), FILE_DIMENSIONS_4X4, ACTION_NONE,      (1), (0)) \
    FILE_X(FILE_ASIA_CASTLE_SHADOW,                                   (97), FILE_GRAPHICS_NONE, FILE_PRIO_SHADOW,   (1), TYPE_SHADOW,              (0),      (0),    (0),    (0),     (1),  (0),  (0),  (1), FILE_DIMENSIONS_4X4, ACTION_NONE,      (1), (0)) \
    FILE_X(FILE_ARAB_CASTLE_SHADOW,                                   (98), FILE_GRAPHICS_NONE, FILE_PRIO_SHADOW,   (1), TYPE_SHADOW,              (0),      (0),    (0),    (0),     (1),  (0),  (0),  (1), FILE_DIMENSIONS_4X4, ACTION_NONE,      (1), (0)) \
    FILE_X(FILE_WEST_EUROPE_CASTLE_SHADOW,                            (99), FILE_GRAPHICS_NONE, FILE_PRIO_SHADOW,   (1), TYPE_SHADOW,              (0),      (0),    (0),    (0),     (1),  (0),  (0),  (1), FILE_DIMENSIONS_4X4, ACTION_NONE,      (1), (0)) \
    FILE_X(FILE_NORTH_EUROPE_CASTLE,                                 (100), FILE_GRAPHICS_NONE, FILE_PRIO_BUILDING, (0), TYPE_CASTLE,              (0),    (100),    (0),    (0),     (1),  (0),  (0),  (1), FILE_DIMENSIONS_4X4, ACTION_UNIT_TECH, (0), (0)) \
    FILE_X(FILE_ASIA_CASTLE,                                         (101), FILE_GRAPHICS_NONE, FILE_PRIO_BUILDING, (0), TYPE_CASTLE,              (0),    (100),    (0),    (0),     (1),  (0),  (0),  (1), FILE_DIMENSIONS_4X4, ACTION_UNIT_TECH, (0), (0)) \
    FILE_X(FILE_ARAB_CASTLE,                                         (102), FILE_GRAPHICS_NONE, FILE_PRIO_BUILDING, (0), TYPE_CASTLE,              (0),    (100),    (0),    (0),     (1),  (0),  (0),  (1), FILE_DIMENSIONS_4X4, ACTION_UNIT_TECH, (0), (0)) \
    FILE_X(FILE_WEST_EUROPE_CASTLE,                                  (103), FILE_GRAPHICS_NONE, FILE_PRIO_BUILDING, (0), TYPE_CASTLE,              (0),    (100),    (0),    (0),     (1),  (0),  (0),  (1), FILE_DIMENSIONS_4X4, ACTION_UNIT_TECH, (0), (0)) \
    FILE_X(FILE_FIRE_SMALL_A,                                        (148), FILE_GRAPHICS_NONE, FILE_PRIO_UNIT,     (1), TYPE_FIRE,                (0),      (0),    (0),    (0),     (0),  (0),  (0),  (0), FILE_DIMENSIONS_1X1, ACTION_NONE,      (1), (0)) \
    FILE_X(FILE_FIRE_SMALL_B,                                        (149), FILE_GRAPHICS_NONE, FILE_PRIO_UNIT,     (1), TYPE_FIRE,                (0),      (0),    (0),    (0),     (0),  (0),  (0),  (0), FILE_DIMENSIONS_1X1, ACTION_NONE,      (1), (0)) \
    FILE_X(FILE_FIRE_SMALL_C,                                        (150), FILE_GRAPHICS_NONE, FILE_PRIO_UNIT,     (1), TYPE_FIRE,                (0),      (0),    (0),    (0),     (0),  (0),  (0),  (0), FILE_DIMENSIONS_1X1, ACTION_NONE,      (1), (0)) \
    FILE_X(FILE_FIRE_MEDIUM_A,                                       (151), FILE_GRAPHICS_NONE, FILE_PRIO_UNIT,     (1), TYPE_FIRE,                (0),      (0),    (0),    (0),     (0),  (0),  (0),  (0), FILE_DIMENSIONS_1X1, ACTION_NONE,      (1), (0)) \
    FILE_X(FILE_FIRE_MEDIUM_B,                                       (152), FILE_GRAPHICS_NONE, FILE_PRIO_UNIT,     (1), TYPE_FIRE,                (0),      (0),    (0),    (0),     (0),  (0),  (0),  (0), FILE_DIMENSIONS_1X1, ACTION_NONE,      (1), (0)) \
    FILE_X(FILE_FIRE_LARGE_A,                                        (153), FILE_GRAPHICS_NONE, FILE_PRIO_UNIT,     (1), TYPE_FIRE,                (0),      (0),    (0),    (0),     (0),  (0),  (0),  (0), FILE_DIMENSIONS_1X1, ACTION_NONE,      (1), (0)) \
    FILE_X(FILE_FIRE_LARGE_B,                                        (154), FILE_GRAPHICS_NONE, FILE_PRIO_UNIT,     (1), TYPE_FIRE,                (0),      (0),    (0),    (0),     (0),  (0),  (0),  (0), FILE_DIMENSIONS_1X1, ACTION_NONE,      (1), (0)) \
    FILE_X(FILE_FIRE_LARGE_C,                                        (155), FILE_GRAPHICS_NONE, FILE_PRIO_UNIT,     (1), TYPE_FIRE,                (0),      (0),    (0),    (0),     (0),  (0),  (0),  (0), FILE_DIMENSIONS_1X1, ACTION_NONE,      (1), (0)) \
    FILE_X(FILE_FIRE_LARGE_D,                                        (156), FILE_GRAPHICS_NONE, FILE_PRIO_UNIT,     (1), TYPE_FIRE,                (0),      (0),    (0),    (0),     (0),  (0),  (0),  (0), FILE_DIMENSIONS_1X1, ACTION_NONE,      (1), (0)) \
    FILE_X(FILE_KNIGHT_FIGHTING,                                     (190), FILE_GRAPHICS_NONE, FILE_PRIO_UNIT,     (1), TYPE_KNIGHT,              (0),      (0),    (0),    (0),     (0),  (1),  (0),  (0), FILE_DIMENSIONS_1X1, ACTION_COMMAND,   (0), (0)) \
    FILE_X(FILE_KNIGHT_FALLING,                                      (191), FILE_GRAPHICS_NONE, FILE_PRIO_UNIT,     (1), TYPE_KNIGHT,              (0),      (0),    (0),    (0),     (0),  (1),  (0),  (0), FILE_DIMENSIONS_1X1, ACTION_COMMAND,   (0), (0)) \
    FILE_X(FILE_KNIGHT_IDLE,                                         (192), FILE_GRAPHICS_NONE, FILE_PRIO_UNIT,     (1), TYPE_KNIGHT,            (180),    (100),   (13), (3800),     (0),  (1),  (0),  (0), FILE_DIMENSIONS_1X1, ACTION_COMMAND,   (0), (0)) \
    FILE_X(FILE_KNIGHT_DECAYING,                                     (193), FILE_GRAPHICS_NONE, FILE_PRIO_DECAY,    (1), TYPE_KNIGHT,              (0),      (0),    (0),    (0),     (0),  (1),  (0),  (0), FILE_DIMENSIONS_1X1, ACTION_COMMAND,   (0), (0)) \
    FILE_X(FILE_KNIGHT_MOVING,                                       (194), FILE_GRAPHICS_NONE, FILE_PRIO_UNIT,     (1), TYPE_KNIGHT,              (0),      (0),    (0),    (0),     (0),  (1),  (0),  (0), FILE_DIMENSIONS_1X1, ACTION_COMMAND,   (0), (0)) \
    FILE_X(FILE_AGE_2_NORTH_EUROPE_MILL_SHADOW,                      (216), FILE_GRAPHICS_NONE, FILE_PRIO_BUILDING, (0), TYPE_NONE,                (0),      (0),    (0),    (0),     (0),  (0),  (0),  (1), FILE_DIMENSIONS_2X2, ACTION_UNIT_TECH, (1), (0)) \
    FILE_X(FILE_AGE_2_ARAB_MILL_SHADOW,                              (217), FILE_GRAPHICS_NONE, FILE_PRIO_BUILDING, (0), TYPE_NONE,                (0),      (0),    (0),    (0),     (0),  (0),  (0),  (1), FILE_DIMENSIONS_2X2, ACTION_UNIT_TECH, (1), (0)) \
    FILE_X(FILE_AGE_2_WEST_EUROPE_MILL_SHADOW,                       (218), FILE_GRAPHICS_NONE, FILE_PRIO_BUILDING, (0), TYPE_NONE,                (0),      (0),    (0),    (0),     (0),  (0),  (0),  (1), FILE_DIMENSIONS_2X2, ACTION_UNIT_TECH, (1), (0)) \
    FILE_X(FILE_AGE_2_NORTH_EUROPE_MILL_ANIMATION,                   (219), FILE_GRAPHICS_NONE, FILE_PRIO_BUILDING, (0), TYPE_NONE,                (0),      (0),    (0),    (0),     (0),  (0),  (0),  (1), FILE_DIMENSIONS_2X2, ACTION_UNIT_TECH, (1), (0)) \
    FILE_X(FILE_AGE_2_ASIA_MILL_ANIMATION,                           (220), FILE_GRAPHICS_NONE, FILE_PRIO_BUILDING, (0), TYPE_NONE,                (0),      (0),    (0),    (0),     (0),  (0),  (0),  (1), FILE_DIMENSIONS_2X2, ACTION_UNIT_TECH, (1), (0)) \
    FILE_X(FILE_AGE_2_ARAB_MILL_ANIMATION,                           (221), FILE_GRAPHICS_NONE, FILE_PRIO_BUILDING, (0), TYPE_NONE,                (0),      (0),    (0),    (0),     (0),  (0),  (0),  (1), FILE_DIMENSIONS_2X2, ACTION_UNIT_TECH, (1), (0)) \
    FILE_X(FILE_AGE_2_WEST_EUROPE_MILL_ANIMATION,                    (222), FILE_GRAPHICS_NONE, FILE_PRIO_BUILDING, (0), TYPE_NONE,                (0),      (0),    (0),    (0),     (0),  (0),  (0),  (1), FILE_DIMENSIONS_2X2, ACTION_UNIT_TECH, (1), (0)) \
    FILE_X(FILE_AGE_2_NORTH_EUROPE_MILL,                             (223), FILE_GRAPHICS_NONE, FILE_PRIO_BUILDING, (0), TYPE_MILL,                (0),    (100),    (0),    (0),     (1),  (0),  (0),  (1), FILE_DIMENSIONS_2X2, ACTION_UNIT_TECH, (0), (0)) \
    FILE_X(FILE_AGE_2_ASIA_MILL,                                     (224), FILE_GRAPHICS_NONE, FILE_PRIO_BUILDING, (0), TYPE_MILL,                (0),    (100),    (0),    (0),     (1),  (0),  (0),  (1), FILE_DIMENSIONS_2X2, ACTION_UNIT_TECH, (0), (0)) \
    FILE_X(FILE_AGE_2_ARAB_MILL,                                     (225), FILE_GRAPHICS_NONE, FILE_PRIO_BUILDING, (0), TYPE_MILL,                (0),    (100),    (0),    (0),     (1),  (0),  (0),  (1), FILE_DIMENSIONS_2X2, ACTION_UNIT_TECH, (0), (0)) \
    FILE_X(FILE_AGE_2_WEST_EUROPE_MILL,                              (226), FILE_GRAPHICS_NONE, FILE_PRIO_BUILDING, (0), TYPE_MILL,                (0),    (100),    (0),    (0),     (1),  (0),  (0),  (1), FILE_DIMENSIONS_2X2, ACTION_UNIT_TECH, (0), (0)) \
    FILE_X(FILE_AGE_3_NORTH_EUROPE_MILL_SHADOW,                      (227), FILE_GRAPHICS_NONE, FILE_PRIO_BUILDING, (0), TYPE_NONE,                (0),      (0),    (0),    (0),     (0),  (0),  (0),  (1), FILE_DIMENSIONS_2X2, ACTION_UNIT_TECH, (1), (0)) \
    FILE_X(FILE_AGE_3_ARAB_MILL_SHADOW,                              (228), FILE_GRAPHICS_NONE, FILE_PRIO_BUILDING, (0), TYPE_NONE,                (0),      (0),    (0),    (0),     (0),  (0),  (0),  (1), FILE_DIMENSIONS_2X2, ACTION_UNIT_TECH, (1), (0)) \
    FILE_X(FILE_AGE_3_WEST_EUROPE_MILL_SHADOW,                       (229), FILE_GRAPHICS_NONE, FILE_PRIO_BUILDING, (0), TYPE_NONE,                (0),      (0),    (0),    (0),     (0),  (0),  (0),  (1), FILE_DIMENSIONS_2X2, ACTION_UNIT_TECH, (1), (0)) \
    FILE_X(FILE_AGE_3_NORTH_EUROPE_MILL_ANIMATION,                   (230), FILE_GRAPHICS_NONE, FILE_PRIO_BUILDING, (0), TYPE_NONE,                (0),      (0),    (0),    (0),     (0),  (0),  (0),  (1), FILE_DIMENSIONS_2X2, ACTION_UNIT_TECH, (1), (0)) \
    FILE_X(FILE_AGE_3_ASIA_MILL_ANIMATION,                           (231), FILE_GRAPHICS_NONE, FILE_PRIO_BUILDING, (0), TYPE_NONE,                (0),      (0),    (0),    (0),     (0),  (0),  (0),  (1), FILE_DIMENSIONS_2X2, ACTION_UNIT_TECH, (1), (0)) \
    FILE_X(FILE_AGE_3_ARAB_MILL_ANIMATION,                           (232), FILE_GRAPHICS_NONE, FILE_PRIO_BUILDING, (0), TYPE_NONE,                (0),      (0),    (0),    (0),     (0),  (0),  (0),  (1), FILE_DIMENSIONS_2X2, ACTION_UNIT_TECH, (1), (0)) \
    FILE_X(FILE_AGE_3_WEST_EUROPE_MILL_ANIMATION,                    (233), FILE_GRAPHICS_NONE, FILE_PRIO_BUILDING, (0), TYPE_NONE,                (0),      (0),    (0),    (0),     (0),  (0),  (0),  (1), FILE_DIMENSIONS_2X2, ACTION_UNIT_TECH, (1), (0)) \
    FILE_X(FILE_AGE_3_NORTH_EUROPE_MILL,                             (234), FILE_GRAPHICS_NONE, FILE_PRIO_BUILDING, (0), TYPE_MILL,                (0),    (100),    (0),    (0),     (1),  (0),  (0),  (1), FILE_DIMENSIONS_2X2, ACTION_UNIT_TECH, (0), (0)) \
    FILE_X(FILE_AGE_3_ASIA_MILL,                                     (235), FILE_GRAPHICS_NONE, FILE_PRIO_BUILDING, (0), TYPE_MILL,                (0),    (100),    (0),    (0),     (1),  (0),  (0),  (1), FILE_DIMENSIONS_2X2, ACTION_UNIT_TECH, (0), (0)) \
    FILE_X(FILE_AGE_3_ARAB_MILL,                                     (236), FILE_GRAPHICS_NONE, FILE_PRIO_BUILDING, (0), TYPE_MILL,                (0),    (100),    (0),    (0),     (1),  (0),  (0),  (1), FILE_DIMENSIONS_2X2, ACTION_UNIT_TECH, (0), (0)) \
    FILE_X(FILE_AGE_3_WEST_EUROPE_MILL,                              (237), FILE_GRAPHICS_NONE, FILE_PRIO_BUILDING, (0), TYPE_MILL,                (0),    (100),    (0),    (0),     (1),  (0),  (0),  (1), FILE_DIMENSIONS_2X2, ACTION_UNIT_TECH, (0), (0)) \
    FILE_X(FILE_AGE_1_TOWN_CENTER_SHADOW,                            (268), FILE_GRAPHICS_NONE, FILE_PRIO_SHADOW,   (1), TYPE_SHADOW,              (0),      (0),    (0),    (0),     (1),  (0),  (0),  (1), FILE_DIMENSIONS_3X3, ACTION_NONE,      (1), (0)) \
    FILE_X(FILE_AGE_2_NORTH_EUROPE_TOWN_CENTER_SHADOW,               (270), FILE_GRAPHICS_NONE, FILE_PRIO_SHADOW,   (1), TYPE_SHADOW,              (0),      (0),    (0),    (0),     (1),  (0),  (0),  (1), FILE_DIMENSIONS_3X3, ACTION_NONE,      (1), (0)) \
    FILE_X(FILE_AGE_2_ASIA_TOWN_CENTER_SHADOW,                       (271), FILE_GRAPHICS_NONE, FILE_PRIO_SHADOW,   (1), TYPE_SHADOW,              (0),      (0),    (0),    (0),     (1),  (0),  (0),  (1), FILE_DIMENSIONS_3X3, ACTION_NONE,      (1), (0)) \
    FILE_X(FILE_AGE_2_ARAB_TOWN_CENTER_SHADOW,                       (272), FILE_GRAPHICS_NONE, FILE_PRIO_SHADOW,   (1), TYPE_SHADOW,              (0),      (0),    (0),    (0),     (1),  (0),  (0),  (1), FILE_DIMENSIONS_3X3, ACTION_NONE,      (1), (0)) \
    FILE_X(FILE_AGE_2_WEST_EUROPE_TOWN_CENTER_SHADOW,                (273), FILE_GRAPHICS_NONE, FILE_PRIO_SHADOW,   (1), TYPE_SHADOW,              (0),      (0),    (0),    (0),     (1),  (0),  (0),  (1), FILE_DIMENSIONS_3X3, ACTION_NONE,      (1), (0)) \
    FILE_X(FILE_AGE_3_NORTH_EUROPE_TOWN_CENTER_SHADOW,               (279), FILE_GRAPHICS_NONE, FILE_PRIO_SHADOW,   (1), TYPE_SHADOW,              (0),      (0),    (0),    (0),     (1),  (0),  (0),  (1), FILE_DIMENSIONS_3X3, ACTION_NONE,      (1), (0)) \
    FILE_X(FILE_AGE_3_ASIA_TOWN_CENTER_SHADOW,                       (280), FILE_GRAPHICS_NONE, FILE_PRIO_SHADOW,   (1), TYPE_SHADOW,              (0),      (0),    (0),    (0),     (1),  (0),  (0),  (1), FILE_DIMENSIONS_3X3, ACTION_NONE,      (1), (0)) \
    FILE_X(FILE_AGE_3_ARAB_TOWN_CENTER_SHADOW,                       (281), FILE_GRAPHICS_NONE, FILE_PRIO_SHADOW,   (1), TYPE_SHADOW,              (0),      (0),    (0),    (0),     (1),  (0),  (0),  (1), FILE_DIMENSIONS_3X3, ACTION_NONE,      (1), (0)) \
    FILE_X(FILE_AGE_3_WEST_EUROPE_TOWN_CENTER_SHADOW,                (282), FILE_GRAPHICS_NONE, FILE_PRIO_SHADOW,   (1), TYPE_SHADOW,              (0),      (0),    (0),    (0),     (1),  (0),  (0),  (1), FILE_DIMENSIONS_3X3, ACTION_NONE,      (1), (0)) \
    FILE_X(FILE_AGE_4_NORTH_EUROPE_TOWN_CENTER_SHADOW,               (287), FILE_GRAPHICS_NONE, FILE_PRIO_SHADOW,   (1), TYPE_SHADOW,              (0),      (0),    (0),    (0),     (1),  (0),  (0),  (1), FILE_DIMENSIONS_3X3, ACTION_NONE,      (1), (0)) \
    FILE_X(FILE_AGE_4_ASIA_TOWN_CENTER_SHADOW,                       (288), FILE_GRAPHICS_NONE, FILE_PRIO_SHADOW,   (1), TYPE_SHADOW,              (0),      (0),    (0),    (0),     (1),  (0),  (0),  (1), FILE_DIMENSIONS_3X3, ACTION_NONE,      (1), (0)) \
    FILE_X(FILE_AGE_4_ARAB_TOWN_CENTER_SHADOW,                       (289), FILE_GRAPHICS_NONE, FILE_PRIO_SHADOW,   (1), TYPE_SHADOW,              (0),      (0),    (0),    (0),     (1),  (0),  (0),  (1), FILE_DIMENSIONS_3X3, ACTION_NONE,      (1), (0)) \
    FILE_X(FILE_AGE_4_WEST_EUROPE_TOWN_CENTER_SHADOW,                (290), FILE_GRAPHICS_NONE, FILE_PRIO_SHADOW,   (1), TYPE_SHADOW,              (0),      (0),    (0),    (0),     (1),  (0),  (0),  (1), FILE_DIMENSIONS_3X3, ACTION_NONE,      (1), (0)) \
    FILE_X(FILE_AGE_1_TOWN_CENTER_TOP,                               (269), FILE_GRAPHICS_NONE, FILE_PRIO_BUILDING, (0), TYPE_TOWN_CENTER,         (0),    (100),    (0),    (0),     (1),  (0),  (0),  (1), FILE_DIMENSIONS_3X3, ACTION_UNIT_TECH, (0), (0)) \
    FILE_X(FILE_AGE_2_NORTH_EUROPE_TOWN_CENTER_TOP,                  (275), FILE_GRAPHICS_NONE, FILE_PRIO_BUILDING, (0), TYPE_TOWN_CENTER,         (0),    (100),    (0),    (0),     (1),  (0),  (0),  (1), FILE_DIMENSIONS_3X3, ACTION_UNIT_TECH, (0), (0)) \
    FILE_X(FILE_AGE_2_ASIA_TOWN_CENTER_TOP,                          (276), FILE_GRAPHICS_NONE, FILE_PRIO_BUILDING, (0), TYPE_TOWN_CENTER,         (0),    (100),    (0),    (0),     (1),  (0),  (0),  (1), FILE_DIMENSIONS_3X3, ACTION_UNIT_TECH, (0), (0)) \
    FILE_X(FILE_AGE_2_ARAB_TOWN_CENTER_TOP,                          (277), FILE_GRAPHICS_NONE, FILE_PRIO_BUILDING, (0), TYPE_TOWN_CENTER,         (0),    (100),    (0),    (0),     (1),  (0),  (0),  (1), FILE_DIMENSIONS_3X3, ACTION_UNIT_TECH, (0), (0)) \
    FILE_X(FILE_AGE_2_WEST_EUROPE_TOWN_CENTER_TOP,                   (278), FILE_GRAPHICS_NONE, FILE_PRIO_BUILDING, (0), TYPE_TOWN_CENTER,         (0),    (100),    (0),    (0),     (1),  (0),  (0),  (1), FILE_DIMENSIONS_3X3, ACTION_UNIT_TECH, (0), (0)) \
    FILE_X(FILE_AGE_3_NORTH_EUROPE_TOWN_CENTER_TOP,                  (283), FILE_GRAPHICS_NONE, FILE_PRIO_BUILDING, (0), TYPE_TOWN_CENTER,         (0),    (100),    (0),    (0),     (1),  (0),  (0),  (1), FILE_DIMENSIONS_3X3, ACTION_UNIT_TECH, (0), (0)) \
    FILE_X(FILE_AGE_3_ASIA_TOWN_CENTER_TOP,                          (284), FILE_GRAPHICS_NONE, FILE_PRIO_BUILDING, (0), TYPE_TOWN_CENTER,         (0),    (100),    (0),    (0),     (1),  (0),  (0),  (1), FILE_DIMENSIONS_3X3, ACTION_UNIT_TECH, (0), (0)) \
    FILE_X(FILE_AGE_3_ARAB_TOWN_CENTER_TOP,                          (285), FILE_GRAPHICS_NONE, FILE_PRIO_BUILDING, (0), TYPE_TOWN_CENTER,         (0),    (100),    (0),    (0),     (1),  (0),  (0),  (1), FILE_DIMENSIONS_3X3, ACTION_UNIT_TECH, (0), (0)) \
    FILE_X(FILE_AGE_3_WEST_EUROPE_TOWN_CENTER_TOP,                   (286), FILE_GRAPHICS_NONE, FILE_PRIO_BUILDING, (0), TYPE_TOWN_CENTER,         (0),    (100),    (0),    (0),     (1),  (0),  (0),  (1), FILE_DIMENSIONS_3X3, ACTION_UNIT_TECH, (0), (0)) \
    FILE_X(FILE_AGE_4_NORTH_EUROPE_TOWN_CENTER_FLOORING,             (291), FILE_GRAPHICS_NONE, FILE_PRIO_DECAY,    (1), TYPE_TOWN_CENTER,         (0),      (0),    (0),    (0),     (1),  (0),  (0),  (1), FILE_DIMENSIONS_3X3, ACTION_NONE,      (1), (0)) \
    FILE_X(FILE_AGE_4_ASIA_TOWN_CENTER_FLOORING,                     (292), FILE_GRAPHICS_NONE, FILE_PRIO_DECAY,    (1), TYPE_TOWN_CENTER,         (0),      (0),    (0),    (0),     (1),  (0),  (0),  (1), FILE_DIMENSIONS_3X3, ACTION_NONE,      (1), (0)) \
    FILE_X(FILE_AGE_4_ARAB_TOWN_CENTER_FLOORING,                     (293), FILE_GRAPHICS_NONE, FILE_PRIO_DECAY,    (1), TYPE_TOWN_CENTER,         (0),      (0),    (0),    (0),     (1),  (0),  (0),  (1), FILE_DIMENSIONS_3X3, ACTION_NONE,      (1), (0)) \
    FILE_X(FILE_AGE_4_WEST_EUROPE_TOWN_CENTER_FLOORING,              (294), FILE_GRAPHICS_NONE, FILE_PRIO_DECAY,    (1), TYPE_TOWN_CENTER,         (0),      (0),    (0),    (0),     (1),  (0),  (0),  (1), FILE_DIMENSIONS_3X3, ACTION_NONE,      (1), (0)) \
    FILE_X(FILE_AGE_4_NORTH_EUROPE_TOWN_CENTER_TOP,                  (295), FILE_GRAPHICS_NONE, FILE_PRIO_BUILDING, (0), TYPE_TOWN_CENTER,         (0),    (100),    (0),    (0),     (1),  (0),  (0),  (1), FILE_DIMENSIONS_3X3, ACTION_UNIT_TECH, (0), (0)) \
    FILE_X(FILE_AGE_4_ASIA_TOWN_CENTER_TOP,                          (296), FILE_GRAPHICS_NONE, FILE_PRIO_BUILDING, (0), TYPE_TOWN_CENTER,         (0),    (100),    (0),    (0),     (1),  (0),  (0),  (1), FILE_DIMENSIONS_3X3, ACTION_UNIT_TECH, (0), (0)) \
    FILE_X(FILE_AGE_4_ARAB_TOWN_CENTER_TOP,                          (297), FILE_GRAPHICS_NONE, FILE_PRIO_BUILDING, (0), TYPE_TOWN_CENTER,         (0),    (100),    (0),    (0),     (1),  (0),  (0),  (1), FILE_DIMENSIONS_3X3, ACTION_UNIT_TECH, (0), (0)) \
    FILE_X(FILE_AGE_4_WEST_EUROPE_TOWN_CENTER_TOP,                   (298), FILE_GRAPHICS_NONE, FILE_PRIO_BUILDING, (0), TYPE_TOWN_CENTER,         (0),    (100),    (0),    (0),     (1),  (0),  (0),  (1), FILE_DIMENSIONS_3X3, ACTION_UNIT_TECH, (0), (0)) \
    FILE_X(FILE_RUBBLE_1X1,                                          (299), FILE_GRAPHICS_NONE, FILE_PRIO_DECAY,    (1), TYPE_RUBBLE,              (0),      (0),    (0),    (0),     (1),  (0),  (0),  (0), FILE_DIMENSIONS_1X1, ACTION_NONE,      (1), (0)) \
    FILE_X(FILE_RUBBLE_2X2,                                          (300), FILE_GRAPHICS_NONE, FILE_PRIO_DECAY,    (1), TYPE_RUBBLE,              (0),      (0),    (0),    (0),     (1),  (0),  (0),  (0), FILE_DIMENSIONS_2X2, ACTION_NONE,      (1), (0)) \
    FILE_X(FILE_RUBBLE_3X3,                                          (301), FILE_GRAPHICS_NONE, FILE_PRIO_DECAY,    (1), TYPE_RUBBLE,              (0),      (0),    (0),    (0),     (1),  (0),  (0),  (0), FILE_DIMENSIONS_3X3, ACTION_NONE,      (1), (0)) \
    FILE_X(FILE_RUBBLE_4X4,                                          (302), FILE_GRAPHICS_NONE, FILE_PRIO_DECAY,    (1), TYPE_RUBBLE,              (0),      (0),    (0),    (0),     (1),  (0),  (0),  (0), FILE_DIMENSIONS_4X4, ACTION_NONE,      (1), (0)) \
    FILE_X(FILE_MILITIA_FIGHTING,                                    (321), FILE_GRAPHICS_NONE, FILE_PRIO_UNIT,     (1), TYPE_MILITIA,             (0),      (0),    (0),    (0),     (0),  (1),  (0),  (0), FILE_DIMENSIONS_1X1, ACTION_COMMAND,   (0), (0)) \
    FILE_X(FILE_MILITIA_FALLING,                                     (322), FILE_GRAPHICS_NONE, FILE_PRIO_UNIT,     (1), TYPE_MILITIA,             (0),      (0),    (0),    (0),     (0),  (1),  (0),  (0), FILE_DIMENSIONS_1X1, ACTION_COMMAND,   (0), (0)) \
    FILE_X(FILE_MILITIA_IDLE,                                        (323), FILE_GRAPHICS_NONE, FILE_PRIO_UNIT,     (1), TYPE_MILITIA,           (120),    (100),    (5), (2500),     (0),  (1),  (0),  (0), FILE_DIMENSIONS_1X1, ACTION_COMMAND,   (0), (0)) \
    FILE_X(FILE_MILITIA_DECAYING,                                    (324), FILE_GRAPHICS_NONE, FILE_PRIO_DECAY,    (1), TYPE_MILITIA,             (0),      (0),    (0),    (0),     (0),  (1),  (0),  (0), FILE_DIMENSIONS_1X1, ACTION_COMMAND,   (0), (0)) \
    FILE_X(FILE_MILITIA_MOVING,                                      (325), FILE_GRAPHICS_NONE, FILE_PRIO_UNIT,     (1), TYPE_MILITIA,             (0),      (0),    (0),    (0),     (0),  (1),  (0),  (0), FILE_DIMENSIONS_1X1, ACTION_COMMAND,   (0), (0)) \
    FILE_X(FILE_RUBBLE_5X5,                                          (304), FILE_GRAPHICS_NONE, FILE_PRIO_DECAY,    (1), TYPE_RUBBLE,              (0),      (0),    (0),    (0),     (1),  (0),  (0),  (0), FILE_DIMENSIONS_5X5, ACTION_NONE,      (1), (0)) \
    FILE_X(FILE_STONE_MINE,                                          (334), FILE_GRAPHICS_NONE, FILE_PRIO_UNIT,     (0), TYPE_STONE_MINE,          (0), (999999),    (0),    (0),     (1),  (0),  (0),  (1), FILE_DIMENSIONS_1X1, ACTION_NONE,      (0), (0)) \
    FILE_X(FILE_TREE_STUMPS,                                         (335), FILE_GRAPHICS_NONE, FILE_PRIO_DECAY,    (1), TYPE_RUBBLE,              (0),      (0),    (0),    (0),     (1),  (0),  (0),  (0), FILE_DIMENSIONS_1X1, ACTION_NONE,      (1), (0)) \
    FILE_X(FILE_TEUTONIC_KNIGHT_FIGHTING,                            (359), FILE_GRAPHICS_NONE, FILE_PRIO_UNIT,     (1), TYPE_TEUTONIC_KNIGHT,     (0),      (0),    (0),    (0),     (0),  (1),  (0),  (0), FILE_DIMENSIONS_1X1, ACTION_COMMAND,   (0), (0)) \
    FILE_X(FILE_TEUTONIC_KNIGHT_FALLING,                             (360), FILE_GRAPHICS_NONE, FILE_PRIO_UNIT,     (1), TYPE_TEUTONIC_KNIGHT,     (0),      (0),    (0),    (0),     (0),  (1),  (0),  (0), FILE_DIMENSIONS_1X1, ACTION_COMMAND,   (0), (0)) \
    FILE_X(FILE_TEUTONIC_KNIGHT_IDLE,                                (361), FILE_GRAPHICS_NONE, FILE_PRIO_UNIT,     (1), TYPE_TEUTONIC_KNIGHT,   (100),    (100),   (18), (2500),     (0),  (1),  (0),  (0), FILE_DIMENSIONS_1X1, ACTION_COMMAND,   (0), (0)) \
    FILE_X(FILE_TEUTONIC_KNIGHT_DECAYING,                            (362), FILE_GRAPHICS_NONE, FILE_PRIO_DECAY,    (1), TYPE_TEUTONIC_KNIGHT,     (0),      (0),    (0),    (0),     (0),  (1),  (0),  (0), FILE_DIMENSIONS_1X1, ACTION_COMMAND,   (0), (0)) \
    FILE_X(FILE_TEUTONIC_KNIGHT_MOVING,                              (363), FILE_GRAPHICS_NONE, FILE_PRIO_UNIT,     (1), TYPE_TEUTONIC_KNIGHT,     (0),      (0),    (0),    (0),     (0),  (1),  (0),  (0), FILE_DIMENSIONS_1X1, ACTION_COMMAND,   (0), (0)) \
    FILE_X(FILE_FEMALE_VILLAGER_FIGHTING,                            (402), FILE_GRAPHICS_NONE, FILE_PRIO_UNIT,     (1), TYPE_VILLAGER,            (0),      (0),    (0),    (0),     (0),  (1),  (0),  (0), FILE_DIMENSIONS_1X1, ACTION_BUILD,     (0), (0)) \
    FILE_X(FILE_FEMALE_VILLAGER_FALLING,                             (403), FILE_GRAPHICS_NONE, FILE_PRIO_UNIT,     (1), TYPE_VILLAGER,            (0),      (0),    (0),    (0),     (0),  (1),  (0),  (0), FILE_DIMENSIONS_1X1, ACTION_BUILD,     (0), (0)) \
    FILE_X(FILE_FEMALE_VILLAGER_IDLE,                                (404), FILE_GRAPHICS_NONE, FILE_PRIO_UNIT,     (1), TYPE_VILLAGER,          (120),    (100),    (5), (2500),     (0),  (1),  (0),  (0), FILE_DIMENSIONS_1X1, ACTION_BUILD,     (0), (0)) \
    FILE_X(FILE_FEMALE_VILLAGER_DECAYING,                            (405), FILE_GRAPHICS_NONE, FILE_PRIO_DECAY,    (1), TYPE_VILLAGER,            (0),      (0),    (0),    (0),     (0),  (1),  (0),  (0), FILE_DIMENSIONS_1X1, ACTION_BUILD,     (0), (0)) \
    FILE_X(FILE_FEMALE_VILLAGER_MOVING,                              (406), FILE_GRAPHICS_NONE, FILE_PRIO_UNIT,     (1), TYPE_VILLAGER,            (0),      (0),    (0),    (0),     (0),  (1),  (0),  (0), FILE_DIMENSIONS_1X1, ACTION_BUILD,     (0), (0)) \
    FILE_X(FILE_MALE_VILLAGER_FIGHTING,                              (430), FILE_GRAPHICS_NONE, FILE_PRIO_UNIT,     (1), TYPE_VILLAGER,            (0),      (0),    (0),    (0),     (0),  (1),  (0),  (0), FILE_DIMENSIONS_1X1, ACTION_BUILD,     (0), (0)) \
    FILE_X(FILE_MALE_VILLAGER_FALLING,                               (431), FILE_GRAPHICS_NONE, FILE_PRIO_UNIT,     (1), TYPE_VILLAGER,            (0),      (0),    (0),    (0),     (0),  (1),  (0),  (0), FILE_DIMENSIONS_1X1, ACTION_BUILD,     (0), (0)) \
    FILE_X(FILE_MALE_VILLAGER_IDLE,                                  (432), FILE_GRAPHICS_NONE, FILE_PRIO_UNIT,     (1), TYPE_VILLAGER,          (120),    (100),    (5), (2500),     (0),  (1),  (0),  (0), FILE_DIMENSIONS_1X1, ACTION_BUILD,     (0), (0)) \
    FILE_X(FILE_MALE_VILLAGER_DECAYING,                              (433), FILE_GRAPHICS_NONE, FILE_PRIO_DECAY,    (1), TYPE_VILLAGER,            (0),      (0),    (0),    (0),     (0),  (1),  (0),  (0), FILE_DIMENSIONS_1X1, ACTION_BUILD,     (0), (0)) \
    FILE_X(FILE_MALE_VILLAGER_MOVING,                                (434), FILE_GRAPHICS_NONE, FILE_PRIO_UNIT,     (1), TYPE_VILLAGER,            (0),      (0),    (0),    (0),     (0),  (1),  (0),  (0), FILE_DIMENSIONS_1X1, ACTION_BUILD,     (0), (0)) \
    FILE_X(FILE_MALE_VILLAGER_WOODCUTTER_CHOPPING,                   (452), FILE_GRAPHICS_NONE, FILE_PRIO_UNIT,     (1), TYPE_VILLAGER,            (0),      (0),    (0),    (0),     (0),  (1),  (0),  (0), FILE_DIMENSIONS_1X1, ACTION_BUILD,     (0), (0)) \
    FILE_X(FILE_MALE_VILLAGER_WOODCUTTER_CARRYING,                   (453), FILE_GRAPHICS_NONE, FILE_PRIO_UNIT,     (1), TYPE_VILLAGER,            (0),      (0),    (0),    (0),     (0),  (1),  (0),  (0), FILE_DIMENSIONS_1X1, ACTION_BUILD,     (0), (0)) \
    FILE_X(FILE_MALE_VILLAGER_WOODCUTTER_FALLING,                    (454), FILE_GRAPHICS_NONE, FILE_PRIO_UNIT,     (1), TYPE_VILLAGER,            (0),      (0),    (0),    (0),     (0),  (1),  (0),  (0), FILE_DIMENSIONS_1X1, ACTION_BUILD,     (0), (0)) \
    FILE_X(FILE_MALE_VILLAGER_WOODCUTTER_IDLE,                       (455), FILE_GRAPHICS_NONE, FILE_PRIO_UNIT,     (1), TYPE_VILLAGER,          (120),    (100),    (5), (2500),     (0),  (1),  (0),  (0), FILE_DIMENSIONS_1X1, ACTION_BUILD,     (0), (0)) \
    FILE_X(FILE_MALE_VILLAGER_WOODCUTTER_DECAYING,                   (456), FILE_GRAPHICS_NONE, FILE_PRIO_DECAY,    (1), TYPE_VILLAGER,            (0),      (0),    (0),    (0),     (0),  (1),  (0),  (0), FILE_DIMENSIONS_1X1, ACTION_BUILD,     (0), (0)) \
    FILE_X(FILE_AGE_1_HOUSE,                                         (568), FILE_GRAPHICS_NONE, FILE_PRIO_BUILDING, (0), TYPE_HOUSE,               (0),    (100),    (0),    (0),     (1),  (0),  (0),  (1), FILE_DIMENSIONS_2X2, ACTION_UNIT_TECH, (0), (0)) \
    FILE_X(FILE_AGE_2_NORTH_EUROPE_HOUSE,                            (569), FILE_GRAPHICS_NONE, FILE_PRIO_BUILDING, (0), TYPE_HOUSE,               (0),    (100),    (0),    (0),     (1),  (0),  (0),  (1), FILE_DIMENSIONS_2X2, ACTION_UNIT_TECH, (0), (0)) \
    FILE_X(FILE_AGE_2_ASIA_HOUSE,                                    (570), FILE_GRAPHICS_NONE, FILE_PRIO_BUILDING, (0), TYPE_HOUSE,               (0),    (100),    (0),    (0),     (1),  (0),  (0),  (1), FILE_DIMENSIONS_2X2, ACTION_UNIT_TECH, (0), (0)) \
    FILE_X(FILE_AGE_2_ARAB_HOUSE,                                    (571), FILE_GRAPHICS_NONE, FILE_PRIO_BUILDING, (0), TYPE_HOUSE,               (0),    (100),    (0),    (0),     (1),  (0),  (0),  (1), FILE_DIMENSIONS_2X2, ACTION_UNIT_TECH, (0), (0)) \
    FILE_X(FILE_AGE_2_WEST_EUROPE_HOUSE,                             (572), FILE_GRAPHICS_NONE, FILE_PRIO_BUILDING, (0), TYPE_HOUSE,               (0),    (100),    (0),    (0),     (1),  (0),  (0),  (1), FILE_DIMENSIONS_2X2, ACTION_UNIT_TECH, (0), (0)) \
    FILE_X(FILE_AGE_3_NORTH_EUROPE_HOUSE,                            (573), FILE_GRAPHICS_NONE, FILE_PRIO_BUILDING, (0), TYPE_HOUSE,               (0),    (100),    (0),    (0),     (1),  (0),  (0),  (1), FILE_DIMENSIONS_2X2, ACTION_UNIT_TECH, (0), (0)) \
    FILE_X(FILE_AGE_3_ASIA_HOUSE,                                    (574), FILE_GRAPHICS_NONE, FILE_PRIO_BUILDING, (0), TYPE_HOUSE,               (0),    (100),    (0),    (0),     (1),  (0),  (0),  (1), FILE_DIMENSIONS_2X2, ACTION_UNIT_TECH, (0), (0)) \
    FILE_X(FILE_AGE_3_ARAB_HOUSE,                                    (575), FILE_GRAPHICS_NONE, FILE_PRIO_BUILDING, (0), TYPE_HOUSE,               (0),    (100),    (0),    (0),     (1),  (0),  (0),  (1), FILE_DIMENSIONS_2X2, ACTION_UNIT_TECH, (0), (0)) \
    FILE_X(FILE_AGE_3_WEST_EUROPE_HOUSE,                             (576), FILE_GRAPHICS_NONE, FILE_PRIO_BUILDING, (0), TYPE_HOUSE,               (0),    (100),    (0),    (0),     (1),  (0),  (0),  (1), FILE_DIMENSIONS_2X2, ACTION_UNIT_TECH, (0), (0)) \
    FILE_X(FILE_FOREST_TREE_SHADOW,                                  (587), FILE_GRAPHICS_NONE, FILE_PRIO_SHADOW,   (1), TYPE_SHADOW,              (0),      (0),    (0),    (0),     (1),  (0),  (0),  (1), FILE_DIMENSIONS_1X1, ACTION_NONE,      (1), (0)) \
    FILE_X(FILE_BERRY_BUSH,                                          (698), FILE_GRAPHICS_NONE, FILE_PRIO_UNIT,     (0), TYPE_BERRY_BUSH,          (0), (999999),    (0),    (0),     (1),  (0),  (0),  (1), FILE_DIMENSIONS_1X1, ACTION_NONE,      (0), (0)) \
    FILE_X(FILE_AGE_1_BARRACKS,                                      (729), FILE_GRAPHICS_NONE, FILE_PRIO_BUILDING, (0), TYPE_BARRACKS,            (0),    (100),    (0),    (0),     (1),  (0),  (0),  (1), FILE_DIMENSIONS_3X3, ACTION_UNIT_TECH, (0), (0)) \
    FILE_X(FILE_WAYPOINT_FLAG,                                       (795), FILE_GRAPHICS_NONE, FILE_PRIO_UNIT,     (1), TYPE_NONE,                (0),      (0),    (0),    (0),     (0),  (0),  (0),  (0), FILE_DIMENSIONS_1X1, ACTION_NONE,      (1), (0)) \
    FILE_X(FILE_RIGHT_CLICK_RED_ARROWS,                              (796), FILE_GRAPHICS_NONE, FILE_PRIO_UNIT,     (1), TYPE_NONE,                (0),      (0),    (0),    (0),     (0),  (0),  (1),  (0), FILE_DIMENSIONS_1X1, ACTION_NONE,      (1), (0)) \
    FILE_X(FILE_AGE_4_NORTH_EUROPE_TOWN_CENTER_ROOF_LEFT,            (798), FILE_GRAPHICS_NONE, FILE_PRIO_BUILDING, (1), TYPE_TOWN_CENTER,         (0),      (0),    (0),    (0),     (1),  (0),  (0),  (1), FILE_DIMENSIONS_2X1, ACTION_NONE,      (1), (0)) \
    FILE_X(FILE_AGE_4_ASIA_TOWN_CENTER_ROOF_LEFT,                    (799), FILE_GRAPHICS_NONE, FILE_PRIO_BUILDING, (1), TYPE_TOWN_CENTER,         (0),      (0),    (0),    (0),     (1),  (0),  (0),  (1), FILE_DIMENSIONS_2X1, ACTION_NONE,      (1), (0)) \
    FILE_X(FILE_AGE_4_ARAB_TOWN_CENTER_ROOF_LEFT,                    (800), FILE_GRAPHICS_NONE, FILE_PRIO_BUILDING, (1), TYPE_TOWN_CENTER,         (0),      (0),    (0),    (0),     (1),  (0),  (0),  (1), FILE_DIMENSIONS_2X1, ACTION_NONE,      (1), (0)) \
    FILE_X(FILE_AGE_4_WEST_EUROPE_TOWN_CENTER_ROOF_LEFT,             (801), FILE_GRAPHICS_NONE, FILE_PRIO_BUILDING, (1), TYPE_TOWN_CENTER,         (0),      (0),    (0),    (0),     (1),  (0),  (0),  (1), FILE_DIMENSIONS_2X1, ACTION_NONE,      (1), (0)) \
    FILE_X(FILE_AGE_4_NORTH_EUROPE_TOWN_CENTER_ROOF_LEFT_SUPPORT_A,  (802), FILE_GRAPHICS_NONE, FILE_PRIO_BUILDING, (1), TYPE_TOWN_CENTER,         (0),      (0),    (0),    (0),     (1),  (0),  (0),  (1), FILE_DIMENSIONS_1X1, ACTION_NONE,      (1), (1)) \
    FILE_X(FILE_AGE_4_ASIA_TOWN_CENTER_ROOF_LEFT_SUPPORT_A,          (803), FILE_GRAPHICS_NONE, FILE_PRIO_BUILDING, (1), TYPE_TOWN_CENTER,         (0),      (0),    (0),    (0),     (1),  (0),  (0),  (1), FILE_DIMENSIONS_1X1, ACTION_NONE,      (1), (1)) \
    FILE_X(FILE_AGE_4_ARAB_TOWN_CENTER_ROOF_LEFT_SUPPORT_A,          (804), FILE_GRAPHICS_NONE, FILE_PRIO_BUILDING, (1), TYPE_TOWN_CENTER,         (0),      (0),    (0),    (0),     (1),  (0),  (0),  (1), FILE_DIMENSIONS_1X1, ACTION_NONE,      (1), (1)) \
    FILE_X(FILE_AGE_4_WEST_EUROPE_TOWN_CENTER_ROOF_LEFT_SUPPORT_A,   (805), FILE_GRAPHICS_NONE, FILE_PRIO_BUILDING, (1), TYPE_TOWN_CENTER,         (0),      (0),    (0),    (0),     (1),  (0),  (0),  (1), FILE_DIMENSIONS_1X1, ACTION_NONE,      (1), (1)) \
    FILE_X(FILE_AGE_4_NORTH_EUROPE_TOWN_CENTER_ROOF_LEFT_SUPPORT_B,  (806), FILE_GRAPHICS_NONE, FILE_PRIO_BUILDING, (1), TYPE_TOWN_CENTER,         (0),      (0),    (0),    (0),     (1),  (0),  (0),  (1), FILE_DIMENSIONS_1X1, ACTION_NONE,      (1), (0)) \
    FILE_X(FILE_AGE_4_ASIA_TOWN_CENTER_ROOF_LEFT_SUPPORT_B,          (807), FILE_GRAPHICS_NONE, FILE_PRIO_BUILDING, (1), TYPE_TOWN_CENTER,         (0),      (0),    (0),    (0),     (1),  (0),  (0),  (1), FILE_DIMENSIONS_1X1, ACTION_NONE,      (1), (0)) \
    FILE_X(FILE_AGE_4_ARAB_TOWN_CENTER_ROOF_LEFT_SUPPORT_B,          (808), FILE_GRAPHICS_NONE, FILE_PRIO_BUILDING, (1), TYPE_TOWN_CENTER,         (0),      (0),    (0),    (0),     (1),  (0),  (0),  (1), FILE_DIMENSIONS_1X1, ACTION_NONE,      (1), (0)) \
    FILE_X(FILE_AGE_4_WEST_EUROPE_TOWN_CENTER_ROOF_LEFT_SUPPORT_B,   (809), FILE_GRAPHICS_NONE, FILE_PRIO_BUILDING, (1), TYPE_TOWN_CENTER,         (0),      (0),    (0),    (0),     (1),  (0),  (0),  (1), FILE_DIMENSIONS_1X1, ACTION_NONE,      (1), (0)) \
    FILE_X(FILE_AGE_1_MILL_DONKEY,                                   (811), FILE_GRAPHICS_NONE, FILE_PRIO_BUILDING, (0), TYPE_NONE,                (0),      (0),    (0),    (0),     (0),  (0),  (0),  (1), FILE_DIMENSIONS_2X2, ACTION_UNIT_TECH, (1), (0)) \
    FILE_X(FILE_AGE_1_MILL,                                          (812), FILE_GRAPHICS_NONE, FILE_PRIO_BUILDING, (0), TYPE_MILL,                (0),    (100),    (0),    (0),     (1),  (0),  (0),  (1), FILE_DIMENSIONS_2X2, ACTION_UNIT_TECH, (0), (0)) \
    FILE_X(FILE_NORTH_EUROPE_STONE_MINING_CAMP,                      (813), FILE_GRAPHICS_NONE, FILE_PRIO_BUILDING, (0), TYPE_MINING_CAMP,         (0),    (100),    (0),    (0),     (1),  (0),  (0),  (1), FILE_DIMENSIONS_2X2, ACTION_UNIT_TECH, (0), (0)) \
    FILE_X(FILE_ASIA_STONE_MINING_CAMP,                              (814), FILE_GRAPHICS_NONE, FILE_PRIO_BUILDING, (0), TYPE_MINING_CAMP,         (0),    (100),    (0),    (0),     (1),  (0),  (0),  (1), FILE_DIMENSIONS_2X2, ACTION_UNIT_TECH, (0), (0)) \
    FILE_X(FILE_ARAB_STONE_MINING_CAMP,                              (815), FILE_GRAPHICS_NONE, FILE_PRIO_BUILDING, (0), TYPE_MINING_CAMP,         (0),    (100),    (0),    (0),     (1),  (0),  (0),  (1), FILE_DIMENSIONS_2X2, ACTION_UNIT_TECH, (0), (0)) \
    FILE_X(FILE_WEST_EUROPE_STONE_MINING_CAMP,                       (816), FILE_GRAPHICS_NONE, FILE_PRIO_BUILDING, (0), TYPE_MINING_CAMP,         (0),    (100),    (0),    (0),     (1),  (0),  (0),  (1), FILE_DIMENSIONS_2X2, ACTION_UNIT_TECH, (0), (0)) \
    FILE_X(FILE_NORTH_EUROPE_LUMBER_CAMP,                            (817), FILE_GRAPHICS_NONE, FILE_PRIO_BUILDING, (0), TYPE_LUMBER_CAMP,         (0),    (100),    (0),    (0),     (1),  (0),  (0),  (1), FILE_DIMENSIONS_2X2, ACTION_UNIT_TECH, (0), (0)) \
    FILE_X(FILE_ASIA_LUMBER_CAMP,                                    (818), FILE_GRAPHICS_NONE, FILE_PRIO_BUILDING, (0), TYPE_LUMBER_CAMP,         (0),    (100),    (0),    (0),     (1),  (0),  (0),  (1), FILE_DIMENSIONS_2X2, ACTION_UNIT_TECH, (0), (0)) \
    FILE_X(FILE_ARAB_LUMBER_CAMP,                                    (819), FILE_GRAPHICS_NONE, FILE_PRIO_BUILDING, (0), TYPE_LUMBER_CAMP,         (0),    (100),    (0),    (0),     (1),  (0),  (0),  (1), FILE_DIMENSIONS_2X2, ACTION_UNIT_TECH, (0), (0)) \
    FILE_X(FILE_WEST_EUROPE_LUMBER_CAMP,                             (820), FILE_GRAPHICS_NONE, FILE_PRIO_BUILDING, (0), TYPE_LUMBER_CAMP,         (0),    (100),    (0),    (0),     (1),  (0),  (0),  (1), FILE_DIMENSIONS_2X2, ACTION_UNIT_TECH, (0), (0)) \
    FILE_X(FILE_WONDER_BRITONS,                                      (832), FILE_GRAPHICS_NONE, FILE_PRIO_BUILDING, (0), TYPE_WONDER,              (0),    (100),    (0),    (0),     (1),  (0),  (0),  (1), FILE_DIMENSIONS_6X6, ACTION_UNIT_TECH, (0), (0)) \
    FILE_X(FILE_FLAG_TALL,                                           (864), FILE_GRAPHICS_NONE, FILE_PRIO_UNIT,     (1), TYPE_FLAG,                (0),      (0),    (0),    (0),     (0),  (0),  (0),  (0), FILE_DIMENSIONS_1X1, ACTION_NONE,      (1), (0)) \
    FILE_X(FILE_AGE_1_TOWN_CENTER_ROOF_LEFT,                         (870), FILE_GRAPHICS_NONE, FILE_PRIO_BUILDING, (1), TYPE_TOWN_CENTER,         (0),      (0),    (0),    (0),     (1),  (0),  (0),  (1), FILE_DIMENSIONS_2X1, ACTION_NONE,      (1), (0)) \
    FILE_X(FILE_AGE_1_TOWN_CENTER_ROOF_LEFT_SUPPORT_A,               (871), FILE_GRAPHICS_NONE, FILE_PRIO_BUILDING, (1), TYPE_TOWN_CENTER,         (0),      (0),    (0),    (0),     (1),  (0),  (0),  (1), FILE_DIMENSIONS_1X1, ACTION_NONE,      (1), (1)) \
    FILE_X(FILE_AGE_1_TOWN_CENTER_ROOF_LEFT_SUPPORT_B,               (872), FILE_GRAPHICS_NONE, FILE_PRIO_BUILDING, (1), TYPE_TOWN_CENTER,         (0),      (0),    (0),    (0),     (1),  (0),  (0),  (1), FILE_DIMENSIONS_1X1, ACTION_NONE,      (1), (0)) \
    FILE_X(FILE_AGE_2_NORTH_EUROPE_TOWN_CENTER_ROOF_LEFT,            (873), FILE_GRAPHICS_NONE, FILE_PRIO_BUILDING, (1), TYPE_TOWN_CENTER,         (0),      (0),    (0),    (0),     (1),  (0),  (0),  (1), FILE_DIMENSIONS_2X1, ACTION_NONE,      (1), (0)) \
    FILE_X(FILE_AGE_2_ASIA_TOWN_CENTER_ROOF_LEFT,                    (874), FILE_GRAPHICS_NONE, FILE_PRIO_BUILDING, (1), TYPE_TOWN_CENTER,         (0),      (0),    (0),    (0),     (1),  (0),  (0),  (1), FILE_DIMENSIONS_2X1, ACTION_NONE,      (1), (0)) \
    FILE_X(FILE_AGE_2_ARAB_TOWN_CENTER_ROOF_LEFT,                    (875), FILE_GRAPHICS_NONE, FILE_PRIO_BUILDING, (1), TYPE_TOWN_CENTER,         (0),      (0),    (0),    (0),     (1),  (0),  (0),  (1), FILE_DIMENSIONS_2X1, ACTION_NONE,      (1), (0)) \
    FILE_X(FILE_AGE_2_WEST_EUROPE_TOWN_CENTER_ROOF_LEFT,             (876), FILE_GRAPHICS_NONE, FILE_PRIO_BUILDING, (1), TYPE_TOWN_CENTER,         (0),      (0),    (0),    (0),     (1),  (0),  (0),  (1), FILE_DIMENSIONS_2X1, ACTION_NONE,      (1), (0)) \
    FILE_X(FILE_AGE_2_NORTH_EUROPE_TOWN_CENTER_ROOF_LEFT_SUPPORT_A,  (877), FILE_GRAPHICS_NONE, FILE_PRIO_BUILDING, (1), TYPE_TOWN_CENTER,         (0),      (0),    (0),    (0),     (1),  (0),  (0),  (1), FILE_DIMENSIONS_1X1, ACTION_NONE,      (1), (1)) \
    FILE_X(FILE_AGE_2_ASIA_TOWN_CENTER_ROOF_LEFT_SUPPORT_A,          (878), FILE_GRAPHICS_NONE, FILE_PRIO_BUILDING, (1), TYPE_TOWN_CENTER,         (0),      (0),    (0),    (0),     (1),  (0),  (0),  (1), FILE_DIMENSIONS_1X1, ACTION_NONE,      (1), (1)) \
    FILE_X(FILE_AGE_2_ARAB_TOWN_CENTER_ROOF_LEFT_SUPPORT_A,          (879), FILE_GRAPHICS_NONE, FILE_PRIO_BUILDING, (1), TYPE_TOWN_CENTER,         (0),      (0),    (0),    (0),     (1),  (0),  (0),  (1), FILE_DIMENSIONS_1X1, ACTION_NONE,      (1), (1)) \
    FILE_X(FILE_AGE_2_WEST_EUROPE_TOWN_CENTER_ROOF_LEFT_SUPPORT_A,   (880), FILE_GRAPHICS_NONE, FILE_PRIO_BUILDING, (1), TYPE_TOWN_CENTER,         (0),      (0),    (0),    (0),     (1),  (0),  (0),  (1), FILE_DIMENSIONS_1X1, ACTION_NONE,      (1), (1)) \
    FILE_X(FILE_AGE_2_NORTH_EUROPE_TOWN_CENTER_ROOF_LEFT_SUPPORT_B,  (881), FILE_GRAPHICS_NONE, FILE_PRIO_BUILDING, (1), TYPE_TOWN_CENTER,         (0),      (0),    (0),    (0),     (1),  (0),  (0),  (1), FILE_DIMENSIONS_1X1, ACTION_NONE,      (1), (0)) \
    FILE_X(FILE_AGE_2_ASIA_TOWN_CENTER_ROOF_LEFT_SUPPORT_B,          (882), FILE_GRAPHICS_NONE, FILE_PRIO_BUILDING, (1), TYPE_TOWN_CENTER,         (0),      (0),    (0),    (0),     (1),  (0),  (0),  (1), FILE_DIMENSIONS_1X1, ACTION_NONE,      (1), (0)) \
    FILE_X(FILE_AGE_2_ARAB_TOWN_CENTER_ROOF_LEFT_SUPPORT_B,          (883), FILE_GRAPHICS_NONE, FILE_PRIO_BUILDING, (1), TYPE_TOWN_CENTER,         (0),      (0),    (0),    (0),     (1),  (0),  (0),  (1), FILE_DIMENSIONS_1X1, ACTION_NONE,      (1), (0)) \
    FILE_X(FILE_AGE_2_WEST_EUROPE_TOWN_CENTER_ROOF_LEFT_SUPPORT_B,   (884), FILE_GRAPHICS_NONE, FILE_PRIO_BUILDING, (1), TYPE_TOWN_CENTER,         (0),      (0),    (0),    (0),     (1),  (0),  (0),  (1), FILE_DIMENSIONS_1X1, ACTION_NONE,      (1), (0)) \
    FILE_X(FILE_AGE_3_NORTH_EUROPE_TOWN_CENTER_ROOF_LEFT,            (885), FILE_GRAPHICS_NONE, FILE_PRIO_BUILDING, (1), TYPE_TOWN_CENTER,         (0),      (0),    (0),    (0),     (1),  (0),  (0),  (1), FILE_DIMENSIONS_2X1, ACTION_NONE,      (1), (0)) \
    FILE_X(FILE_AGE_3_ASIA_TOWN_CENTER_ROOF_LEFT,                    (886), FILE_GRAPHICS_NONE, FILE_PRIO_BUILDING, (1), TYPE_TOWN_CENTER,         (0),      (0),    (0),    (0),     (1),  (0),  (0),  (1), FILE_DIMENSIONS_2X1, ACTION_NONE,      (1), (0)) \
    FILE_X(FILE_AGE_3_ARAB_TOWN_CENTER_ROOF_LEFT,                    (887), FILE_GRAPHICS_NONE, FILE_PRIO_BUILDING, (1), TYPE_TOWN_CENTER,         (0),      (0),    (0),    (0),     (1),  (0),  (0),  (1), FILE_DIMENSIONS_2X1, ACTION_NONE,      (1), (0)) \
    FILE_X(FILE_AGE_3_WEST_EUROPE_TOWN_CENTER_ROOF_LEFT,             (888), FILE_GRAPHICS_NONE, FILE_PRIO_BUILDING, (1), TYPE_TOWN_CENTER,         (0),      (0),    (0),    (0),     (1),  (0),  (0),  (1), FILE_DIMENSIONS_2X1, ACTION_NONE,      (1), (0)) \
    FILE_X(FILE_AGE_3_NORTH_EUROPE_TOWN_CENTER_ROOF_LEFT_SUPPORT_A,  (889), FILE_GRAPHICS_NONE, FILE_PRIO_BUILDING, (1), TYPE_TOWN_CENTER,         (0),      (0),    (0),    (0),     (1),  (0),  (0),  (1), FILE_DIMENSIONS_1X1, ACTION_NONE,      (1), (1)) \
    FILE_X(FILE_AGE_3_ASIA_TOWN_CENTER_ROOF_LEFT_SUPPORT_A,          (890), FILE_GRAPHICS_NONE, FILE_PRIO_BUILDING, (1), TYPE_TOWN_CENTER,         (0),      (0),    (0),    (0),     (1),  (0),  (0),  (1), FILE_DIMENSIONS_1X1, ACTION_NONE,      (1), (1)) \
    FILE_X(FILE_AGE_3_ARAB_TOWN_CENTER_ROOF_LEFT_SUPPORT_A,          (891), FILE_GRAPHICS_NONE, FILE_PRIO_BUILDING, (1), TYPE_TOWN_CENTER,         (0),      (0),    (0),    (0),     (1),  (0),  (0),  (1), FILE_DIMENSIONS_1X1, ACTION_NONE,      (1), (1)) \
    FILE_X(FILE_AGE_3_WEST_EUROPE_TOWN_CENTER_ROOF_LEFT_SUPPORT_A,   (892), FILE_GRAPHICS_NONE, FILE_PRIO_BUILDING, (1), TYPE_TOWN_CENTER,         (0),      (0),    (0),    (0),     (1),  (0),  (0),  (1), FILE_DIMENSIONS_1X1, ACTION_NONE,      (1), (1)) \
    FILE_X(FILE_AGE_3_NORTH_EUROPE_TOWN_CENTER_ROOF_LEFT_SUPPORT_B,  (893), FILE_GRAPHICS_NONE, FILE_PRIO_BUILDING, (1), TYPE_TOWN_CENTER,         (0),      (0),    (0),    (0),     (1),  (0),  (0),  (1), FILE_DIMENSIONS_1X1, ACTION_NONE,      (1), (0)) \
    FILE_X(FILE_AGE_3_ASIA_TOWN_CENTER_ROOF_LEFT_SUPPORT_B,          (894), FILE_GRAPHICS_NONE, FILE_PRIO_BUILDING, (1), TYPE_TOWN_CENTER,         (0),      (0),    (0),    (0),     (1),  (0),  (0),  (1), FILE_DIMENSIONS_1X1, ACTION_NONE,      (1), (0)) \
    FILE_X(FILE_AGE_3_ARAB_TOWN_CENTER_ROOF_LEFT_SUPPORT_B,          (895), FILE_GRAPHICS_NONE, FILE_PRIO_BUILDING, (1), TYPE_TOWN_CENTER,         (0),      (0),    (0),    (0),     (1),  (0),  (0),  (1), FILE_DIMENSIONS_1X1, ACTION_NONE,      (1), (0)) \
    FILE_X(FILE_AGE_3_WEST_EUROPE_TOWN_CENTER_ROOF_LEFT_SUPPORT_B,   (896), FILE_GRAPHICS_NONE, FILE_PRIO_BUILDING, (1), TYPE_TOWN_CENTER,         (0),      (0),    (0),    (0),     (1),  (0),  (0),  (1), FILE_DIMENSIONS_1X1, ACTION_NONE,      (1), (0)) \
    FILE_X(FILE_AGE_1_OUTPOST,                                      (1259), FILE_GRAPHICS_NONE, FILE_PRIO_BUILDING, (0), TYPE_OUTPOST,             (0),    (100),    (0),    (0),     (1),  (0),  (0),  (1), FILE_DIMENSIONS_1X1, ACTION_UNIT_TECH, (0), (0)) \
    FILE_X(FILE_AGE_1_OUTPOST_SHADOW,                               (1274), FILE_GRAPHICS_NONE, FILE_PRIO_SHADOW,   (1), TYPE_SHADOW,              (0),      (0),    (0),    (0),     (1),  (0),  (0),  (1), FILE_DIMENSIONS_1X1, ACTION_NONE,      (1), (0)) \
    FILE_X(FILE_GOLD_MINE,                                          (1297), FILE_GRAPHICS_NONE, FILE_PRIO_UNIT,     (0), TYPE_GOLD_MINE,           (0), (999999),    (0),    (0),     (1),  (0),  (0),  (1), FILE_DIMENSIONS_1X1, ACTION_NONE,      (0), (0)) \
    FILE_X(FILE_AGE_1_TOWN_CENTER_ROOF_RITE,                        (1370), FILE_GRAPHICS_NONE, FILE_PRIO_BUILDING, (1), TYPE_TOWN_CENTER,         (0),      (0),    (0),    (0),     (1),  (0),  (0),  (1), FILE_DIMENSIONS_2X1, ACTION_NONE,      (1), (0)) \
    FILE_X(FILE_AGE_1_TOWN_CENTER_ROOF_RITE_SUPPORT_A,              (1371), FILE_GRAPHICS_NONE, FILE_PRIO_BUILDING, (1), TYPE_TOWN_CENTER,         (0),      (0),    (0),    (0),     (1),  (0),  (0),  (1), FILE_DIMENSIONS_1X1, ACTION_NONE,      (1), (1)) \
    FILE_X(FILE_AGE_1_TOWN_CENTER_ROOF_RITE_SUPPORT_B,              (1372), FILE_GRAPHICS_NONE, FILE_PRIO_BUILDING, (1), TYPE_TOWN_CENTER,         (0),      (0),    (0),    (0),     (1),  (0),  (0),  (1), FILE_DIMENSIONS_1X1, ACTION_NONE,      (1), (0)) \
    FILE_X(FILE_AGE_2_NORTH_EUROPE_TOWN_CENTER_ROOF_RITE,           (1373), FILE_GRAPHICS_NONE, FILE_PRIO_BUILDING, (1), TYPE_TOWN_CENTER,         (0),      (0),    (0),    (0),     (1),  (0),  (0),  (1), FILE_DIMENSIONS_2X1, ACTION_NONE,      (1), (0)) \
    FILE_X(FILE_AGE_2_ASIA_TOWN_CENTER_ROOF_RITE,                   (1374), FILE_GRAPHICS_NONE, FILE_PRIO_BUILDING, (1), TYPE_TOWN_CENTER,         (0),      (0),    (0),    (0),     (1),  (0),  (0),  (1), FILE_DIMENSIONS_2X1, ACTION_NONE,      (1), (0)) \
    FILE_X(FILE_AGE_2_ARAB_TOWN_CENTER_ROOF_RITE,                   (1375), FILE_GRAPHICS_NONE, FILE_PRIO_BUILDING, (1), TYPE_TOWN_CENTER,         (0),      (0),    (0),    (0),     (1),  (0),  (0),  (1), FILE_DIMENSIONS_2X1, ACTION_NONE,      (1), (0)) \
    FILE_X(FILE_AGE_2_WEST_EUROPE_TOWN_CENTER_ROOF_RITE,            (1376), FILE_GRAPHICS_NONE, FILE_PRIO_BUILDING, (1), TYPE_TOWN_CENTER,         (0),      (0),    (0),    (0),     (1),  (0),  (0),  (1), FILE_DIMENSIONS_2X1, ACTION_NONE,      (1), (0)) \
    FILE_X(FILE_AGE_2_NORTH_EUROPE_TOWN_CENTER_ROOF_RITE_SUPPORT_A, (1377), FILE_GRAPHICS_NONE, FILE_PRIO_BUILDING, (1), TYPE_TOWN_CENTER,         (0),      (0),    (0),    (0),     (1),  (0),  (0),  (1), FILE_DIMENSIONS_1X1, ACTION_NONE,      (1), (1)) \
    FILE_X(FILE_AGE_2_ASIA_TOWN_CENTER_ROOF_RITE_SUPPORT_A,         (1378), FILE_GRAPHICS_NONE, FILE_PRIO_BUILDING, (1), TYPE_TOWN_CENTER,         (0),      (0),    (0),    (0),     (1),  (0),  (0),  (1), FILE_DIMENSIONS_1X1, ACTION_NONE,      (1), (1)) \
    FILE_X(FILE_AGE_2_ARAB_TOWN_CENTER_ROOF_RITE_SUPPORT_A,         (1379), FILE_GRAPHICS_NONE, FILE_PRIO_BUILDING, (1), TYPE_TOWN_CENTER,         (0),      (0),    (0),    (0),     (1),  (0),  (0),  (1), FILE_DIMENSIONS_1X1, ACTION_NONE,      (1), (1)) \
    FILE_X(FILE_AGE_2_WEST_EUROPE_TOWN_CENTER_ROOF_RITE_SUPPORT_A,  (1380), FILE_GRAPHICS_NONE, FILE_PRIO_BUILDING, (1), TYPE_TOWN_CENTER,         (0),      (0),    (0),    (0),     (1),  (0),  (0),  (1), FILE_DIMENSIONS_1X1, ACTION_NONE,      (1), (1)) \
    FILE_X(FILE_AGE_2_NORTH_EUROPE_TOWN_CENTER_ROOF_RITE_SUPPORT_B, (1381), FILE_GRAPHICS_NONE, FILE_PRIO_BUILDING, (1), TYPE_TOWN_CENTER,         (0),      (0),    (0),    (0),     (1),  (0),  (0),  (1), FILE_DIMENSIONS_1X1, ACTION_NONE,      (1), (0)) \
    FILE_X(FILE_AGE_2_ASIA_TOWN_CENTER_ROOF_RITE_SUPPORT_B,         (1382), FILE_GRAPHICS_NONE, FILE_PRIO_BUILDING, (1), TYPE_TOWN_CENTER,         (0),      (0),    (0),    (0),     (1),  (0),  (0),  (1), FILE_DIMENSIONS_1X1, ACTION_NONE,      (1), (0)) \
    FILE_X(FILE_AGE_2_ARAB_TOWN_CENTER_ROOF_RITE_SUPPORT_B,         (1383), FILE_GRAPHICS_NONE, FILE_PRIO_BUILDING, (1), TYPE_TOWN_CENTER,         (0),      (0),    (0),    (0),     (1),  (0),  (0),  (1), FILE_DIMENSIONS_1X1, ACTION_NONE,      (1), (0)) \
    FILE_X(FILE_AGE_2_WEST_EUROPE_TOWN_CENTER_ROOF_RITE_SUPPORT_B,  (1384), FILE_GRAPHICS_NONE, FILE_PRIO_BUILDING, (1), TYPE_TOWN_CENTER,         (0),      (0),    (0),    (0),     (1),  (0),  (0),  (1), FILE_DIMENSIONS_1X1, ACTION_NONE,      (1), (0)) \
    FILE_X(FILE_AGE_3_NORTH_EUROPE_TOWN_CENTER_ROOF_RITE,           (1385), FILE_GRAPHICS_NONE, FILE_PRIO_BUILDING, (1), TYPE_TOWN_CENTER,         (0),      (0),    (0),    (0),     (1),  (0),  (0),  (1), FILE_DIMENSIONS_2X1, ACTION_NONE,      (1), (0)) \
    FILE_X(FILE_AGE_3_ASIA_TOWN_CENTER_ROOF_RITE,                   (1386), FILE_GRAPHICS_NONE, FILE_PRIO_BUILDING, (1), TYPE_TOWN_CENTER,         (0),      (0),    (0),    (0),     (1),  (0),  (0),  (1), FILE_DIMENSIONS_2X1, ACTION_NONE,      (1), (0)) \
    FILE_X(FILE_AGE_3_ARAB_TOWN_CENTER_ROOF_RITE,                   (1387), FILE_GRAPHICS_NONE, FILE_PRIO_BUILDING, (1), TYPE_TOWN_CENTER,         (0),      (0),    (0),    (0),     (1),  (0),  (0),  (1), FILE_DIMENSIONS_2X1, ACTION_NONE,      (1), (0)) \
    FILE_X(FILE_AGE_3_WEST_EUROPE_TOWN_CENTER_ROOF_RITE,            (1388), FILE_GRAPHICS_NONE, FILE_PRIO_BUILDING, (1), TYPE_TOWN_CENTER,         (0),      (0),    (0),    (0),     (1),  (0),  (0),  (1), FILE_DIMENSIONS_2X1, ACTION_NONE,      (1), (0)) \
    FILE_X(FILE_AGE_3_NORTH_EUROPE_TOWN_CENTER_ROOF_RITE_SUPPORT_A, (1389), FILE_GRAPHICS_NONE, FILE_PRIO_BUILDING, (1), TYPE_TOWN_CENTER,         (0),      (0),    (0),    (0),     (1),  (0),  (0),  (1), FILE_DIMENSIONS_1X1, ACTION_NONE,      (1), (1)) \
    FILE_X(FILE_AGE_3_ASIA_TOWN_CENTER_ROOF_RITE_SUPPORT_A,         (1390), FILE_GRAPHICS_NONE, FILE_PRIO_BUILDING, (1), TYPE_TOWN_CENTER,         (0),      (0),    (0),    (0),     (1),  (0),  (0),  (1), FILE_DIMENSIONS_1X1, ACTION_NONE,      (1), (1)) \
    FILE_X(FILE_AGE_3_ARAB_TOWN_CENTER_ROOF_RITE_SUPPORT_A,         (1391), FILE_GRAPHICS_NONE, FILE_PRIO_BUILDING, (1), TYPE_TOWN_CENTER,         (0),      (0),    (0),    (0),     (1),  (0),  (0),  (1), FILE_DIMENSIONS_1X1, ACTION_NONE,      (1), (1)) \
    FILE_X(FILE_AGE_3_WEST_EUROPE_TOWN_CENTER_ROOF_RITE_SUPPORT_A,  (1392), FILE_GRAPHICS_NONE, FILE_PRIO_BUILDING, (1), TYPE_TOWN_CENTER,         (0),      (0),    (0),    (0),     (1),  (0),  (0),  (1), FILE_DIMENSIONS_1X1, ACTION_NONE,      (1), (1)) \
    FILE_X(FILE_AGE_3_NORTH_EUROPE_TOWN_CENTER_ROOF_RITE_SUPPORT_B, (1393), FILE_GRAPHICS_NONE, FILE_PRIO_BUILDING, (1), TYPE_TOWN_CENTER,         (0),      (0),    (0),    (0),     (1),  (0),  (0),  (1), FILE_DIMENSIONS_1X1, ACTION_NONE,      (1), (0)) \
    FILE_X(FILE_AGE_3_ASIA_TOWN_CENTER_ROOF_RITE_SUPPORT_B,         (1394), FILE_GRAPHICS_NONE, FILE_PRIO_BUILDING, (1), TYPE_TOWN_CENTER,         (0),      (0),    (0),    (0),     (1),  (0),  (0),  (1), FILE_DIMENSIONS_1X1, ACTION_NONE,      (1), (0)) \
    FILE_X(FILE_AGE_3_ARAB_TOWN_CENTER_ROOF_RITE_SUPPORT_B,         (1395), FILE_GRAPHICS_NONE, FILE_PRIO_BUILDING, (1), TYPE_TOWN_CENTER,         (0),      (0),    (0),    (0),     (1),  (0),  (0),  (1), FILE_DIMENSIONS_1X1, ACTION_NONE,      (1), (0)) \
    FILE_X(FILE_AGE_3_WEST_EUROPE_TOWN_CENTER_ROOF_RITE_SUPPORT_B,  (1396), FILE_GRAPHICS_NONE, FILE_PRIO_BUILDING, (1), TYPE_TOWN_CENTER,         (0),      (0),    (0),    (0),     (1),  (0),  (0),  (1), FILE_DIMENSIONS_1X1, ACTION_NONE,      (1), (0)) \
    FILE_X(FILE_AGE_4_NORTH_EUROPE_TOWN_CENTER_ROOF_RITE,           (1397), FILE_GRAPHICS_NONE, FILE_PRIO_BUILDING, (1), TYPE_TOWN_CENTER,         (0),      (0),    (0),    (0),     (1),  (0),  (0),  (1), FILE_DIMENSIONS_2X1, ACTION_NONE,      (1), (0)) \
    FILE_X(FILE_AGE_4_ASIA_TOWN_CENTER_ROOF_RITE,                   (1398), FILE_GRAPHICS_NONE, FILE_PRIO_BUILDING, (1), TYPE_TOWN_CENTER,         (0),      (0),    (0),    (0),     (1),  (0),  (0),  (1), FILE_DIMENSIONS_2X1, ACTION_NONE,      (1), (0)) \
    FILE_X(FILE_AGE_4_ARAB_TOWN_CENTER_ROOF_RITE,                   (1399), FILE_GRAPHICS_NONE, FILE_PRIO_BUILDING, (1), TYPE_TOWN_CENTER,         (0),      (0),    (0),    (0),     (1),  (0),  (0),  (1), FILE_DIMENSIONS_2X1, ACTION_NONE,      (1), (0)) \
    FILE_X(FILE_AGE_4_WEST_EUROPE_TOWN_CENTER_ROOF_RITE,            (1400), FILE_GRAPHICS_NONE, FILE_PRIO_BUILDING, (1), TYPE_TOWN_CENTER,         (0),      (0),    (0),    (0),     (1),  (0),  (0),  (1), FILE_DIMENSIONS_2X1, ACTION_NONE,      (1), (0)) \
    FILE_X(FILE_AGE_4_NORTH_EUROPE_TOWN_CENTER_ROOF_RITE_SUPPORT_A, (1401), FILE_GRAPHICS_NONE, FILE_PRIO_BUILDING, (1), TYPE_TOWN_CENTER,         (0),      (0),    (0),    (0),     (1),  (0),  (0),  (1), FILE_DIMENSIONS_1X1, ACTION_NONE,      (1), (1)) \
    FILE_X(FILE_AGE_4_ASIA_TOWN_CENTER_ROOF_RITE_SUPPORT_A,         (1402), FILE_GRAPHICS_NONE, FILE_PRIO_BUILDING, (1), TYPE_TOWN_CENTER,         (0),      (0),    (0),    (0),     (1),  (0),  (0),  (1), FILE_DIMENSIONS_1X1, ACTION_NONE,      (1), (1)) \
    FILE_X(FILE_AGE_4_ARAB_TOWN_CENTER_ROOF_RITE_SUPPORT_A,         (1403), FILE_GRAPHICS_NONE, FILE_PRIO_BUILDING, (1), TYPE_TOWN_CENTER,         (0),      (0),    (0),    (0),     (1),  (0),  (0),  (1), FILE_DIMENSIONS_1X1, ACTION_NONE,      (1), (1)) \
    FILE_X(FILE_AGE_4_WEST_EUROPE_TOWN_CENTER_ROOF_RITE_SUPPORT_A,  (1404), FILE_GRAPHICS_NONE, FILE_PRIO_BUILDING, (1), TYPE_TOWN_CENTER,         (0),      (0),    (0),    (0),     (1),  (0),  (0),  (1), FILE_DIMENSIONS_1X1, ACTION_NONE,      (1), (1)) \
    FILE_X(FILE_AGE_4_NORTH_EUROPE_TOWN_CENTER_ROOF_RITE_SUPPORT_B, (1405), FILE_GRAPHICS_NONE, FILE_PRIO_BUILDING, (1), TYPE_TOWN_CENTER,         (0),      (0),    (0),    (0),     (1),  (0),  (0),  (1), FILE_DIMENSIONS_1X1, ACTION_NONE,      (1), (0)) \
    FILE_X(FILE_AGE_4_ASIA_TOWN_CENTER_ROOF_RITE_SUPPORT_B,         (1406), FILE_GRAPHICS_NONE, FILE_PRIO_BUILDING, (1), TYPE_TOWN_CENTER,         (0),      (0),    (0),    (0),     (1),  (0),  (0),  (1), FILE_DIMENSIONS_1X1, ACTION_NONE,      (1), (0)) \
    FILE_X(FILE_AGE_4_ARAB_TOWN_CENTER_ROOF_RITE_SUPPORT_B,         (1407), FILE_GRAPHICS_NONE, FILE_PRIO_BUILDING, (1), TYPE_TOWN_CENTER,         (0),      (0),    (0),    (0),     (1),  (0),  (0),  (1), FILE_DIMENSIONS_1X1, ACTION_NONE,      (1), (0)) \
    FILE_X(FILE_AGE_4_WEST_EUROPE_TOWN_CENTER_ROOF_RITE_SUPPORT_B,  (1408), FILE_GRAPHICS_NONE, FILE_PRIO_BUILDING, (1), TYPE_TOWN_CENTER,         (0),      (0),    (0),    (0),     (1),  (0),  (0),  (1), FILE_DIMENSIONS_1X1, ACTION_NONE,      (1), (0)) \
    FILE_X(FILE_FOREST_TREE,                                        (1410), FILE_GRAPHICS_NONE, FILE_PRIO_BUILDING, (0), TYPE_TREE,                (0), (999999),    (0),    (0),     (1),  (0),  (0),  (1), FILE_DIMENSIONS_1X1, ACTION_NONE,      (0), (0))
