#pragma once

#include "Type.h"
#include "Action.h"

#include <stdint.h>
#include <stdio.h>
#include <stdbool.h>

typedef struct
{
    int32_t id;
    int32_t data_offset;
    int32_t size;
}
File;

void File_Print(const File);

File File_Load(FILE* const);

#define FILE_NONE (-1)

#define FILE_PRIO_TERRAIN (1U)
#define FILE_PRIO_SHADOW (2U)
#define FILE_PRIO_DECAY (3U)
#define FILE_PRIO_BUILDING (4U)
#define FILE_PRIO_UNIT (5U)
#define FILE_PRIO_HIGHEST (255U)

#define FILE_DIMENSIONS_1X1 {1,1}
#define FILE_DIMENSIONS_2X1 {2,1}
#define FILE_DIMENSIONS_2X2 {2,2}
#define FILE_DIMENSIONS_3X3 {3,3}
#define FILE_DIMENSIONS_4X4 {4,4}
#define FILE_DIMENSIONS_5X5 {5,5}
#define FILE_DIMENSIONS_6X6 {6,6}

// FOR MORE DETAILS ABOUT X-MACROS: HTTPS://EN.WIKIPEDIA.ORG/WIKI/X_MACRO
// THIS X-MACRO IS USED IN: INTERFAC.[CH]. GRAPHICS.[CH], TERRAIN.[CH], REGISTRAR.C
// TO GET AN IDEA OF HOW THE X-MACRO EXPANDS IN GRAPHICS.C, FOR INSTANCE, RUN: GCC -E GRAPHICS.C | CLANG-FORMAT
//  --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
//                                                                      |           |                                                        |                  | W  |                          |       |         |        |         |  S  |  M  |  E  |  I  |                    |                 | D  | M
//                                                                      |           |                                                        |                  | A  |                          |       |         |        |         |  I  |  U  |  X  |  N  |                    |                 | E  | I
//                                                                      |           |                                                        |                  | K  |                          |       |         |        |         |  N  |  L  |  P  |  A  |                    |                 | T  | D
//                                                                      |           |                                                        |                  | A  |                          |       |         |        |         |  G  |  T  |  I  |  N  |                    |                 | A  | D
//                                                                      |           |                                                        |                  | B  |                          |       |         |        |         |  L  |  I  |  R  |  I  |                    |                 | I  | E
//                                                                      |           |                                                        |                  | L  |                          |       |         |        |         |  E  |  S  |  E  |  M  |                    |                 | L  | D
//                                                                      |           |                                                        |                  | E  |                          |       |         |        |         |  F  |  T  |     |  A  |                    |                 |    |
//                                                                      |           |                                                        |                  |    |                          |       |         |        |         |  R  |  A  |     |  T  |                    |                 |    |
//                                                                      |           |                                                        |                  |    |                          |       |         |        |         |  A  |  T  |     |  E  |                    |                 |    |
//                                                                      |           |                                                        |                  |    |                          | MAX   |         |        |         |  M  |  E  |     |     |                    |                 |    |
//  NAME                                                                | FILE      | UPGRADE                                                | PRIO             |    | TYPE                     | SPEED | HEALTH  | ATTACK | WIDTH   |  E  |     |     |     | DIMENSIONS         | ACTION          |    |
//  --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#define FILE_X_INTERFAC                                                                                                                                                                                                                                                                               \
    FILE_X(FILE_INTERFAC_NONE,                                            FILE_NONE, FILE_INTERFAC_NONE,                                      FILE_PRIO_HIGHEST,  (0), TYPE_NONE,                   (0),      (0),    (0),    (0),     (0),  (0),  (0),  (0), FILE_DIMENSIONS_1X1, ACTION_NONE,      (1), (0)) \
    FILE_X(FILE_INTERFAC_BUILDING_ICONS,                                       (31), FILE_INTERFAC_NONE,                                      FILE_PRIO_HIGHEST,  (0), TYPE_NONE,                   (0),      (0),    (0),    (0),     (0),  (0),  (0),  (0), FILE_DIMENSIONS_1X1, ACTION_NONE,      (1), (0)) \
    FILE_X(FILE_INTERFAC_COMMAND_ICONS,                                        (32), FILE_INTERFAC_NONE,                                      FILE_PRIO_HIGHEST,  (0), TYPE_NONE,                   (0),      (0),    (0),    (0),     (0),  (0),  (0),  (0), FILE_DIMENSIONS_1X1, ACTION_NONE,      (1), (0)) \
    FILE_X(FILE_INTERFAC_TECH_ICONS,                                           (34), FILE_INTERFAC_NONE,                                      FILE_PRIO_HIGHEST,  (0), TYPE_NONE,                   (0),      (0),    (0),    (0),     (0),  (0),  (0),  (0), FILE_DIMENSIONS_1X1, ACTION_NONE,      (1), (0)) \
    FILE_X(FILE_INTERFAC_UNIT_ICONS,                                           (35), FILE_INTERFAC_NONE,                                      FILE_PRIO_HIGHEST,  (0), TYPE_NONE,                   (0),      (0),    (0),    (0),     (0),  (0),  (0),  (0), FILE_DIMENSIONS_1X1, ACTION_NONE,      (1), (0)) \
    FILE_X(FILE_INTERFAC_HUD_0,                                                (65), FILE_INTERFAC_NONE,                                      FILE_PRIO_HIGHEST,  (0), TYPE_NONE,                   (0),      (0),    (0),    (0),     (0),  (0),  (0),  (0), FILE_DIMENSIONS_1X1, ACTION_NONE,      (1), (0))
#define FILE_X_TERRAIN                                                                                                                                                                                                                                                                                         \
    FILE_X(FILE_TERRAIN_NONE,                                             FILE_NONE, FILE_GRAPHICS_NONE,                                      FILE_PRIO_HIGHEST,  (1), TYPE_NONE,                   (0),      (0),    (0),    (0),     (0),  (0),  (0),  (0), FILE_DIMENSIONS_1X1, ACTION_NONE,      (1), (0)) \
    FILE_X(FILE_TERRAIN_DIRT,                                                   (0), FILE_GRAPHICS_NONE,                                      FILE_PRIO_TERRAIN,  (1), TYPE_NONE,                   (0),      (0),    (0),    (0),     (0),  (0),  (0),  (0), FILE_DIMENSIONS_1X1, ACTION_NONE,      (1), (0)) \
    FILE_X(FILE_TERRAIN_GRASS_A,                                                (1), FILE_GRAPHICS_NONE,                                      FILE_PRIO_TERRAIN,  (1), TYPE_NONE,                   (0),      (0),    (0),    (0),     (0),  (0),  (0),  (0), FILE_DIMENSIONS_1X1, ACTION_NONE,      (1), (0)) \
    FILE_X(FILE_TERRAIN_WATER_SHALLOW,                                          (2), FILE_GRAPHICS_NONE,                                      FILE_PRIO_TERRAIN,  (0), TYPE_NONE,                   (0),      (0),    (0),    (0),     (0),  (0),  (0),  (0), FILE_DIMENSIONS_1X1, ACTION_NONE,      (1), (0)) \
    FILE_X(FILE_TERRAIN_FARM_READY,                                             (3), FILE_GRAPHICS_NONE,                                      FILE_PRIO_TERRAIN,  (1), TYPE_NONE,                   (0),      (0),    (0),    (0),     (0),  (0),  (0),  (0), FILE_DIMENSIONS_1X1, ACTION_NONE,      (1), (0)) \
    FILE_X(FILE_TERRAIN_FARM_EXAUSTED,                                          (4), FILE_GRAPHICS_NONE,                                      FILE_PRIO_TERRAIN,  (1), TYPE_NONE,                   (0),      (0),    (0),    (0),     (0),  (0),  (0),  (0), FILE_DIMENSIONS_1X1, ACTION_NONE,      (1), (0)) \
    FILE_X(FILE_TERRAIN_GRASS_B,                                                (5), FILE_GRAPHICS_NONE,                                      FILE_PRIO_TERRAIN,  (1), TYPE_NONE,                   (0),      (0),    (0),    (0),     (0),  (0),  (0),  (0), FILE_DIMENSIONS_1X1, ACTION_NONE,      (1), (0)) \
    FILE_X(FILE_TERRAIN_GRASS_C,                                                (6), FILE_GRAPHICS_NONE,                                      FILE_PRIO_TERRAIN,  (1), TYPE_NONE,                   (0),      (0),    (0),    (0),     (0),  (0),  (0),  (0), FILE_DIMENSIONS_1X1, ACTION_NONE,      (1), (0)) \
    FILE_X(FILE_TERRAIN_GRASS_D,                                                (7), FILE_GRAPHICS_NONE,                                      FILE_PRIO_TERRAIN,  (1), TYPE_NONE,                   (0),      (0),    (0),    (0),     (0),  (0),  (0),  (0), FILE_DIMENSIONS_1X1, ACTION_NONE,      (1), (0)) \
    FILE_X(FILE_TERRAIN_GRASS_E,                                                (8), FILE_GRAPHICS_NONE,                                      FILE_PRIO_TERRAIN,  (1), TYPE_NONE,                   (0),      (0),    (0),    (0),     (0),  (0),  (0),  (0), FILE_DIMENSIONS_1X1, ACTION_NONE,      (1), (0)) \
    FILE_X(FILE_TERRAIN_DESERT,                                                 (9), FILE_GRAPHICS_NONE,                                      FILE_PRIO_TERRAIN,  (1), TYPE_NONE,                   (0),      (0),    (0),    (0),     (0),  (0),  (0),  (0), FILE_DIMENSIONS_1X1, ACTION_NONE,      (1), (0)) \
    FILE_X(FILE_TERRAIN_GRASS_LEAVES,                                          (10), FILE_GRAPHICS_NONE,                                      FILE_PRIO_TERRAIN,  (1), TYPE_NONE,                   (0),      (0),    (0),    (0),     (0),  (0),  (0),  (0), FILE_DIMENSIONS_1X1, ACTION_NONE,      (1), (0)) \
    FILE_X(FILE_TERRAIN_WATER_GRASS,                                           (11), FILE_GRAPHICS_NONE,                                      FILE_PRIO_TERRAIN,  (1), TYPE_NONE,                   (0),      (0),    (0),    (0),     (0),  (0),  (0),  (0), FILE_DIMENSIONS_1X1, ACTION_NONE,      (1), (0)) \
    FILE_X(FILE_TERRAIN_WATER_DEEP,                                            (12), FILE_GRAPHICS_NONE,                                      FILE_PRIO_TERRAIN,  (0), TYPE_NONE,                   (0),      (0),    (0),    (0),     (0),  (0),  (0),  (0), FILE_DIMENSIONS_1X1, ACTION_NONE,      (1), (0)) \
    FILE_X(FILE_TERRAIN_WATER_NORMAL,                                          (13), FILE_GRAPHICS_NONE,                                      FILE_PRIO_TERRAIN,  (0), TYPE_NONE,                   (0),      (0),    (0),    (0),     (0),  (0),  (0),  (0), FILE_DIMENSIONS_1X1, ACTION_NONE,      (1), (0)) \
    FILE_X(FILE_TERRAIN_BEACH_SAND,                                            (14), FILE_GRAPHICS_NONE,                                      FILE_PRIO_TERRAIN,  (1), TYPE_NONE,                   (0),      (0),    (0),    (0),     (0),  (0),  (0),  (0), FILE_DIMENSIONS_1X1, ACTION_NONE,      (1), (0)) \
    FILE_X(FILE_TERRAIN_ROAD,                                                  (15), FILE_GRAPHICS_NONE,                                      FILE_PRIO_TERRAIN,  (1), TYPE_NONE,                   (0),      (0),    (0),    (0),     (0),  (0),  (0),  (0), FILE_DIMENSIONS_1X1, ACTION_NONE,      (1), (0)) \
    FILE_X(FILE_TERRAIN_ROAD_WORN,                                             (16), FILE_GRAPHICS_NONE,                                      FILE_PRIO_TERRAIN,  (1), TYPE_NONE,                   (0),      (0),    (0),    (0),     (0),  (0),  (0),  (0), FILE_DIMENSIONS_1X1, ACTION_NONE,      (1), (0)) \
    FILE_X(FILE_TERRAIN_FARM_SOWN,                                             (17), FILE_GRAPHICS_NONE,                                      FILE_PRIO_TERRAIN,  (1), TYPE_NONE,                   (0),      (0),    (0),    (0),     (0),  (0),  (0),  (0), FILE_DIMENSIONS_1X1, ACTION_NONE,      (1), (0)) \
    FILE_X(FILE_TERRAIN_FARM_SPROUT,                                           (18), FILE_GRAPHICS_NONE,                                      FILE_PRIO_TERRAIN,  (1), TYPE_NONE,                   (0),      (0),    (0),    (0),     (0),  (0),  (0),  (0), FILE_DIMENSIONS_1X1, ACTION_NONE,      (1), (0)) \
    FILE_X(FILE_TERRAIN_FARM_GROWING,                                          (19), FILE_GRAPHICS_NONE,                                      FILE_PRIO_TERRAIN,  (1), TYPE_NONE,                   (0),      (0),    (0),    (0),     (0),  (0),  (0),  (0), FILE_DIMENSIONS_1X1, ACTION_NONE,      (1), (0)) \
    FILE_X(FILE_TERRAIN_ICE,                                                   (20), FILE_GRAPHICS_NONE,                                      FILE_PRIO_TERRAIN,  (1), TYPE_NONE,                   (0),      (0),    (0),    (0),     (0),  (0),  (0),  (0), FILE_DIMENSIONS_1X1, ACTION_NONE,      (1), (0))
#define FILE_X_GRAPHICS                                                                                                                                                                                                                                                                                        \
    FILE_X(FILE_GRAPHICS_NONE,                                            FILE_NONE, FILE_GRAPHICS_NONE,                                      FILE_PRIO_HIGHEST,  (1), TYPE_NONE,                   (0),      (0),    (0),    (0),     (0),  (0),  (0),  (0), FILE_DIMENSIONS_1X1, ACTION_NONE,      (1), (0)) \
    FILE_X(FILE_GRAPHICS_SMALLER_EXPLOSION_SMOKE,                              (21), FILE_GRAPHICS_NONE,                                      FILE_PRIO_BUILDING, (1), TYPE_SMOKE,                  (0),      (0),    (0),    (0),     (0),  (0),  (1),  (1), FILE_DIMENSIONS_1X1, ACTION_NONE,      (1), (0)) \
    FILE_X(FILE_GRAPHICS_AGE_2_WEST_EUROPE_BARRACKS,                           (41), FILE_GRAPHICS_AGE_3_WEST_EUROPE_BARRACKS,                FILE_PRIO_BUILDING, (0), TYPE_BARRACKS,               (0),    (100),    (0),    (0),     (1),  (0),  (0),  (1), FILE_DIMENSIONS_3X3, ACTION_UNIT_TECH, (0), (0)) \
    FILE_X(FILE_GRAPHICS_AGE_3_WEST_EUROPE_BARRACKS,                           (45), FILE_GRAPHICS_NONE,                                      FILE_PRIO_BUILDING, (0), TYPE_BARRACKS,               (0),    (100),    (0),    (0),     (1),  (0),  (0),  (1), FILE_DIMENSIONS_3X3, ACTION_UNIT_TECH, (0), (0)) \
    FILE_X(FILE_GRAPHICS_WEST_EUROPE_CASTLE_SHADOW,                            (99), FILE_GRAPHICS_NONE,                                      FILE_PRIO_SHADOW,   (1), TYPE_SHADOW,                 (0),      (0),    (0),    (0),     (1),  (0),  (0),  (1), FILE_DIMENSIONS_4X4, ACTION_NONE,      (1), (0)) \
    FILE_X(FILE_GRAPHICS_WEST_EUROPE_CASTLE,                                  (103), FILE_GRAPHICS_NONE,                                      FILE_PRIO_BUILDING, (0), TYPE_CASTLE,                 (0),    (100),    (0),    (0),     (1),  (0),  (0),  (1), FILE_DIMENSIONS_4X4, ACTION_UNIT_TECH, (0), (0)) \
    FILE_X(FILE_GRAPHICS_FIRE_SMALL_A,                                        (148), FILE_GRAPHICS_NONE,                                      FILE_PRIO_UNIT,     (1), TYPE_FIRE,                   (0),      (0),    (0),    (0),     (0),  (0),  (0),  (0), FILE_DIMENSIONS_1X1, ACTION_NONE,      (1), (0)) \
    FILE_X(FILE_GRAPHICS_FIRE_SMALL_B,                                        (149), FILE_GRAPHICS_NONE,                                      FILE_PRIO_UNIT,     (1), TYPE_FIRE,                   (0),      (0),    (0),    (0),     (0),  (0),  (0),  (0), FILE_DIMENSIONS_1X1, ACTION_NONE,      (1), (0)) \
    FILE_X(FILE_GRAPHICS_FIRE_SMALL_C,                                        (150), FILE_GRAPHICS_NONE,                                      FILE_PRIO_UNIT,     (1), TYPE_FIRE,                   (0),      (0),    (0),    (0),     (0),  (0),  (0),  (0), FILE_DIMENSIONS_1X1, ACTION_NONE,      (1), (0)) \
    FILE_X(FILE_GRAPHICS_FIRE_MEDIUM_A,                                       (151), FILE_GRAPHICS_NONE,                                      FILE_PRIO_UNIT,     (1), TYPE_FIRE,                   (0),      (0),    (0),    (0),     (0),  (0),  (0),  (0), FILE_DIMENSIONS_1X1, ACTION_NONE,      (1), (0)) \
    FILE_X(FILE_GRAPHICS_FIRE_MEDIUM_B,                                       (152), FILE_GRAPHICS_NONE,                                      FILE_PRIO_UNIT,     (1), TYPE_FIRE,                   (0),      (0),    (0),    (0),     (0),  (0),  (0),  (0), FILE_DIMENSIONS_1X1, ACTION_NONE,      (1), (0)) \
    FILE_X(FILE_GRAPHICS_FIRE_LARGE_A,                                        (153), FILE_GRAPHICS_NONE,                                      FILE_PRIO_UNIT,     (1), TYPE_FIRE,                   (0),      (0),    (0),    (0),     (0),  (0),  (0),  (0), FILE_DIMENSIONS_1X1, ACTION_NONE,      (1), (0)) \
    FILE_X(FILE_GRAPHICS_FIRE_LARGE_B,                                        (154), FILE_GRAPHICS_NONE,                                      FILE_PRIO_UNIT,     (1), TYPE_FIRE,                   (0),      (0),    (0),    (0),     (0),  (0),  (0),  (0), FILE_DIMENSIONS_1X1, ACTION_NONE,      (1), (0)) \
    FILE_X(FILE_GRAPHICS_FIRE_LARGE_C,                                        (155), FILE_GRAPHICS_NONE,                                      FILE_PRIO_UNIT,     (1), TYPE_FIRE,                   (0),      (0),    (0),    (0),     (0),  (0),  (0),  (0), FILE_DIMENSIONS_1X1, ACTION_NONE,      (1), (0)) \
    FILE_X(FILE_GRAPHICS_FIRE_LARGE_D,                                        (156), FILE_GRAPHICS_NONE,                                      FILE_PRIO_UNIT,     (1), TYPE_FIRE,                   (0),      (0),    (0),    (0),     (0),  (0),  (0),  (0), FILE_DIMENSIONS_1X1, ACTION_NONE,      (1), (0)) \
    FILE_X(FILE_GRAPHICS_AGE_2_WEST_EUROPE_MILL_SHADOW,                       (218), FILE_GRAPHICS_NONE,                                      FILE_PRIO_BUILDING, (0), TYPE_NONE,                   (0),      (0),    (0),    (0),     (0),  (0),  (0),  (1), FILE_DIMENSIONS_2X2, ACTION_UNIT_TECH, (1), (0)) \
    FILE_X(FILE_GRAPHICS_AGE_2_WEST_EUROPE_MILL_ANIMATION,                    (222), FILE_GRAPHICS_NONE,                                      FILE_PRIO_BUILDING, (0), TYPE_NONE,                   (0),      (0),    (0),    (0),     (0),  (0),  (0),  (1), FILE_DIMENSIONS_2X2, ACTION_UNIT_TECH, (1), (0)) \
    FILE_X(FILE_GRAPHICS_AGE_2_WEST_EUROPE_MILL,                              (226), FILE_GRAPHICS_NONE,                                      FILE_PRIO_BUILDING, (0), TYPE_MILL,                   (0),    (100),    (0),    (0),     (1),  (0),  (0),  (1), FILE_DIMENSIONS_2X2, ACTION_UNIT_TECH, (0), (0)) \
    FILE_X(FILE_GRAPHICS_AGE_3_WEST_EUROPE_MILL_SHADOW,                       (229), FILE_GRAPHICS_NONE,                                      FILE_PRIO_BUILDING, (0), TYPE_NONE,                   (0),      (0),    (0),    (0),     (0),  (0),  (0),  (1), FILE_DIMENSIONS_2X2, ACTION_UNIT_TECH, (1), (0)) \
    FILE_X(FILE_GRAPHICS_AGE_3_WEST_EUROPE_MILL_ANIMATION,                    (233), FILE_GRAPHICS_NONE,                                      FILE_PRIO_BUILDING, (0), TYPE_NONE,                   (0),      (0),    (0),    (0),     (0),  (0),  (0),  (1), FILE_DIMENSIONS_2X2, ACTION_UNIT_TECH, (1), (0)) \
    FILE_X(FILE_GRAPHICS_AGE_3_WEST_EUROPE_MILL,                              (237), FILE_GRAPHICS_NONE,                                      FILE_PRIO_BUILDING, (0), TYPE_MILL,                   (0),    (100),    (0),    (0),     (1),  (0),  (0),  (1), FILE_DIMENSIONS_2X2, ACTION_UNIT_TECH, (0), (0)) \
    FILE_X(FILE_GRAPHICS_AGE_1_TOWN_CENTER_SHADOW,                            (268), FILE_GRAPHICS_NONE,                                      FILE_PRIO_SHADOW,   (1), TYPE_SHADOW,                 (0),      (0),    (0),    (0),     (1),  (0),  (0),  (1), FILE_DIMENSIONS_3X3, ACTION_NONE,      (1), (0)) \
    FILE_X(FILE_GRAPHICS_AGE_2_WEST_EUROPE_TOWN_CENTER_SHADOW,                (273), FILE_GRAPHICS_NONE,                                      FILE_PRIO_SHADOW,   (1), TYPE_SHADOW,                 (0),      (0),    (0),    (0),     (1),  (0),  (0),  (1), FILE_DIMENSIONS_3X3, ACTION_NONE,      (1), (0)) \
    FILE_X(FILE_GRAPHICS_AGE_3_WEST_EUROPE_TOWN_CENTER_SHADOW,                (282), FILE_GRAPHICS_NONE,                                      FILE_PRIO_SHADOW,   (1), TYPE_SHADOW,                 (0),      (0),    (0),    (0),     (1),  (0),  (0),  (1), FILE_DIMENSIONS_3X3, ACTION_NONE,      (1), (0)) \
    FILE_X(FILE_GRAPHICS_AGE_1_TOWN_CENTER_TOP,                               (269), FILE_GRAPHICS_NONE,                                      FILE_PRIO_BUILDING, (0), TYPE_TOWN_CENTER,            (0),    (100),    (0),    (0),     (1),  (0),  (0),  (1), FILE_DIMENSIONS_3X3, ACTION_UNIT_TECH, (0), (0)) \
    FILE_X(FILE_GRAPHICS_AGE_2_WEST_EUROPE_TOWN_CENTER_TOP,                   (278), FILE_GRAPHICS_NONE,                                      FILE_PRIO_BUILDING, (0), TYPE_TOWN_CENTER,            (0),    (100),    (0),    (0),     (1),  (0),  (0),  (1), FILE_DIMENSIONS_3X3, ACTION_UNIT_TECH, (0), (0)) \
    FILE_X(FILE_GRAPHICS_AGE_3_WEST_EUROPE_TOWN_CENTER_TOP,                   (286), FILE_GRAPHICS_NONE,                                      FILE_PRIO_BUILDING, (0), TYPE_TOWN_CENTER,            (0),    (100),    (0),    (0),     (1),  (0),  (0),  (1), FILE_DIMENSIONS_3X3, ACTION_UNIT_TECH, (0), (0)) \
    FILE_X(FILE_GRAPHICS_RUBBLE_1X1,                                          (299), FILE_GRAPHICS_NONE,                                      FILE_PRIO_DECAY,    (1), TYPE_RUBBLE,                 (0),      (0),    (0),    (0),     (1),  (0),  (0),  (0), FILE_DIMENSIONS_1X1, ACTION_NONE,      (1), (0)) \
    FILE_X(FILE_GRAPHICS_RUBBLE_2X2,                                          (300), FILE_GRAPHICS_NONE,                                      FILE_PRIO_DECAY,    (1), TYPE_RUBBLE,                 (0),      (0),    (0),    (0),     (1),  (0),  (0),  (0), FILE_DIMENSIONS_2X2, ACTION_NONE,      (1), (0)) \
    FILE_X(FILE_GRAPHICS_RUBBLE_3X3,                                          (301), FILE_GRAPHICS_NONE,                                      FILE_PRIO_DECAY,    (1), TYPE_RUBBLE,                 (0),      (0),    (0),    (0),     (1),  (0),  (0),  (0), FILE_DIMENSIONS_3X3, ACTION_NONE,      (1), (0)) \
    FILE_X(FILE_GRAPHICS_RUBBLE_4X4,                                          (302), FILE_GRAPHICS_NONE,                                      FILE_PRIO_DECAY,    (1), TYPE_RUBBLE,                 (0),      (0),    (0),    (0),     (1),  (0),  (0),  (0), FILE_DIMENSIONS_4X4, ACTION_NONE,      (1), (0)) \
    FILE_X(FILE_GRAPHICS_MILITIA_FIGHTING,                                    (321), FILE_GRAPHICS_MAN_AT_ARMS_IDLE,                          FILE_PRIO_UNIT,     (1), TYPE_MILITIA,                (0),      (0),    (0),    (0),     (0),  (1),  (0),  (0), FILE_DIMENSIONS_1X1, ACTION_COMMAND,   (0), (0)) \
    FILE_X(FILE_GRAPHICS_MILITIA_FALLING,                                     (322), FILE_GRAPHICS_MAN_AT_ARMS_IDLE,                          FILE_PRIO_UNIT,     (1), TYPE_MILITIA,                (0),      (0),    (0),    (0),     (0),  (1),  (0),  (0), FILE_DIMENSIONS_1X1, ACTION_COMMAND,   (0), (0)) \
    FILE_X(FILE_GRAPHICS_MILITIA_IDLE,                                        (323), FILE_GRAPHICS_MAN_AT_ARMS_IDLE,                          FILE_PRIO_UNIT,     (1), TYPE_MILITIA,              (120),    (100),    (0), (2500),     (0),  (1),  (0),  (0), FILE_DIMENSIONS_1X1, ACTION_COMMAND,   (0), (0)) \
    FILE_X(FILE_GRAPHICS_MILITIA_DECAYING,                                    (324), FILE_GRAPHICS_MAN_AT_ARMS_IDLE,                          FILE_PRIO_DECAY,    (1), TYPE_MILITIA,                (0),      (0),    (0),    (0),     (0),  (1),  (0),  (0), FILE_DIMENSIONS_1X1, ACTION_COMMAND,   (0), (0)) \
    FILE_X(FILE_GRAPHICS_MILITIA_MOVING,                                      (325), FILE_GRAPHICS_MAN_AT_ARMS_IDLE,                          FILE_PRIO_UNIT,     (1), TYPE_MILITIA,                (0),      (0),    (0),    (0),     (0),  (1),  (0),  (0), FILE_DIMENSIONS_1X1, ACTION_COMMAND,   (0), (0)) \
    FILE_X(FILE_GRAPHICS_MAN_AT_ARMS_FIGHTING,                                (336), FILE_GRAPHICS_LONG_SWORDSMAN_IDLE,                       FILE_PRIO_UNIT,     (1), TYPE_MAN_AT_ARMS,            (0),      (0),    (0),    (0),     (0),  (1),  (0),  (0), FILE_DIMENSIONS_1X1, ACTION_COMMAND,   (0), (0)) \
    FILE_X(FILE_GRAPHICS_MAN_AT_ARMS_FALLING,                                 (337), FILE_GRAPHICS_LONG_SWORDSMAN_IDLE,                       FILE_PRIO_UNIT,     (1), TYPE_MAN_AT_ARMS,            (0),      (0),    (0),    (0),     (0),  (1),  (0),  (0), FILE_DIMENSIONS_1X1, ACTION_COMMAND,   (0), (0)) \
    FILE_X(FILE_GRAPHICS_MAN_AT_ARMS_IDLE,                                    (338), FILE_GRAPHICS_LONG_SWORDSMAN_IDLE,                       FILE_PRIO_UNIT,     (1), TYPE_MAN_AT_ARMS,          (120),    (100),    (1), (2500),     (0),  (1),  (0),  (0), FILE_DIMENSIONS_1X1, ACTION_COMMAND,   (0), (0)) \
    FILE_X(FILE_GRAPHICS_MAN_AT_ARMS_DECAYING,                                (339), FILE_GRAPHICS_LONG_SWORDSMAN_IDLE,                       FILE_PRIO_DECAY,    (1), TYPE_MAN_AT_ARMS,            (0),      (0),    (0),    (0),     (0),  (1),  (0),  (0), FILE_DIMENSIONS_1X1, ACTION_COMMAND,   (0), (0)) \
    FILE_X(FILE_GRAPHICS_MAN_AT_ARMS_MOVING,                                  (340), FILE_GRAPHICS_LONG_SWORDSMAN_IDLE,                       FILE_PRIO_UNIT,     (1), TYPE_MAN_AT_ARMS,            (0),      (0),    (0),    (0),     (0),  (1),  (0),  (0), FILE_DIMENSIONS_1X1, ACTION_COMMAND,   (0), (0)) \
    FILE_X(FILE_GRAPHICS_LONG_SWORDSMAN_FIGHTING,                             (354), FILE_GRAPHICS_NONE,                                      FILE_PRIO_UNIT,     (1), TYPE_LONG_SWORDSMAN,         (0),      (0),    (0),    (0),     (0),  (1),  (0),  (0), FILE_DIMENSIONS_1X1, ACTION_COMMAND,   (0), (0)) \
    FILE_X(FILE_GRAPHICS_LONG_SWORDSMAN_FALLING,                              (355), FILE_GRAPHICS_NONE,                                      FILE_PRIO_UNIT,     (1), TYPE_LONG_SWORDSMAN,         (0),      (0),    (0),    (0),     (0),  (1),  (0),  (0), FILE_DIMENSIONS_1X1, ACTION_COMMAND,   (0), (0)) \
    FILE_X(FILE_GRAPHICS_LONG_SWORDSMAN_IDLE,                                 (356), FILE_GRAPHICS_NONE,                                      FILE_PRIO_UNIT,     (1), TYPE_LONG_SWORDSMAN,       (120),    (100),    (1), (2500),     (0),  (1),  (0),  (0), FILE_DIMENSIONS_1X1, ACTION_COMMAND,   (0), (0)) \
    FILE_X(FILE_GRAPHICS_LONG_SWORDSMAN_DECAYING,                             (357), FILE_GRAPHICS_NONE,                                      FILE_PRIO_DECAY,    (1), TYPE_LONG_SWORDSMAN,         (0),      (0),    (0),    (0),     (0),  (1),  (0),  (0), FILE_DIMENSIONS_1X1, ACTION_COMMAND,   (0), (0)) \
    FILE_X(FILE_GRAPHICS_LONG_SWORDSMAN_MOVING,                               (358), FILE_GRAPHICS_NONE,                                      FILE_PRIO_UNIT,     (1), TYPE_LONG_SWORDSMAN,         (0),      (0),    (0),    (0),     (0),  (1),  (0),  (0), FILE_DIMENSIONS_1X1, ACTION_COMMAND,   (0), (0)) \
    FILE_X(FILE_GRAPHICS_RUBBLE_5X5,                                          (304), FILE_GRAPHICS_NONE,                                      FILE_PRIO_DECAY,    (1), TYPE_RUBBLE,                 (0),      (0),    (0),    (0),     (1),  (0),  (0),  (0), FILE_DIMENSIONS_5X5, ACTION_NONE,      (1), (0)) \
    FILE_X(FILE_GRAPHICS_STONE_MINE,                                          (334), FILE_GRAPHICS_NONE,                                      FILE_PRIO_UNIT,     (0), TYPE_STONE_MINE,             (0), (999999),    (0),    (0),     (1),  (0),  (0),  (1), FILE_DIMENSIONS_1X1, ACTION_NONE,      (0), (0)) \
    FILE_X(FILE_GRAPHICS_TREE_STUMPS,                                         (335), FILE_GRAPHICS_NONE,                                      FILE_PRIO_DECAY,    (1), TYPE_RUBBLE,                 (0),      (0),    (0),    (0),     (1),  (0),  (0),  (0), FILE_DIMENSIONS_1X1, ACTION_NONE,      (1), (0)) \
    FILE_X(FILE_GRAPHICS_FEMALE_VILLAGER_FIGHTING,                            (402), FILE_GRAPHICS_NONE,                                      FILE_PRIO_UNIT,     (1), TYPE_VILLAGER,               (0),      (0),    (0),    (0),     (0),  (1),  (0),  (0), FILE_DIMENSIONS_1X1, ACTION_BUILD,     (0), (0)) \
    FILE_X(FILE_GRAPHICS_FEMALE_VILLAGER_FALLING,                             (403), FILE_GRAPHICS_NONE,                                      FILE_PRIO_UNIT,     (1), TYPE_VILLAGER,               (0),      (0),    (0),    (0),     (0),  (1),  (0),  (0), FILE_DIMENSIONS_1X1, ACTION_BUILD,     (0), (0)) \
    FILE_X(FILE_GRAPHICS_FEMALE_VILLAGER_IDLE,                                (404), FILE_GRAPHICS_NONE,                                      FILE_PRIO_UNIT,     (1), TYPE_VILLAGER,             (120),    (100),    (1), (2500),     (0),  (1),  (0),  (0), FILE_DIMENSIONS_1X1, ACTION_BUILD,     (0), (0)) \
    FILE_X(FILE_GRAPHICS_FEMALE_VILLAGER_DECAYING,                            (405), FILE_GRAPHICS_NONE,                                      FILE_PRIO_DECAY,    (1), TYPE_VILLAGER,               (0),      (0),    (0),    (0),     (0),  (1),  (0),  (0), FILE_DIMENSIONS_1X1, ACTION_BUILD,     (0), (0)) \
    FILE_X(FILE_GRAPHICS_FEMALE_VILLAGER_MOVING,                              (406), FILE_GRAPHICS_NONE,                                      FILE_PRIO_UNIT,     (1), TYPE_VILLAGER,               (0),      (0),    (0),    (0),     (0),  (1),  (0),  (0), FILE_DIMENSIONS_1X1, ACTION_BUILD,     (0), (0)) \
    FILE_X(FILE_GRAPHICS_MALE_VILLAGER_FIGHTING,                              (430), FILE_GRAPHICS_NONE,                                      FILE_PRIO_UNIT,     (1), TYPE_VILLAGER,               (0),      (0),    (0),    (0),     (0),  (1),  (0),  (0), FILE_DIMENSIONS_1X1, ACTION_BUILD,     (0), (0)) \
    FILE_X(FILE_GRAPHICS_MALE_VILLAGER_FALLING,                               (431), FILE_GRAPHICS_NONE,                                      FILE_PRIO_UNIT,     (1), TYPE_VILLAGER,               (0),      (0),    (0),    (0),     (0),  (1),  (0),  (0), FILE_DIMENSIONS_1X1, ACTION_BUILD,     (0), (0)) \
    FILE_X(FILE_GRAPHICS_MALE_VILLAGER_IDLE,                                  (432), FILE_GRAPHICS_NONE,                                      FILE_PRIO_UNIT,     (1), TYPE_VILLAGER,             (120),    (100),    (1), (2500),     (0),  (1),  (0),  (0), FILE_DIMENSIONS_1X1, ACTION_BUILD,     (0), (0)) \
    FILE_X(FILE_GRAPHICS_MALE_VILLAGER_DECAYING,                              (433), FILE_GRAPHICS_NONE,                                      FILE_PRIO_DECAY,    (1), TYPE_VILLAGER,               (0),      (0),    (0),    (0),     (0),  (1),  (0),  (0), FILE_DIMENSIONS_1X1, ACTION_BUILD,     (0), (0)) \
    FILE_X(FILE_GRAPHICS_MALE_VILLAGER_MOVING,                                (434), FILE_GRAPHICS_NONE,                                      FILE_PRIO_UNIT,     (1), TYPE_VILLAGER,               (0),      (0),    (0),    (0),     (0),  (1),  (0),  (0), FILE_DIMENSIONS_1X1, ACTION_BUILD,     (0), (0)) \
    FILE_X(FILE_GRAPHICS_AGE_1_HOUSE,                                         (500), FILE_GRAPHICS_AGE_2_WEST_EUROPE_HOUSE,                   FILE_PRIO_BUILDING, (0), TYPE_HOUSE,                  (0),    (100),    (0),    (0),     (1),  (0),  (0),  (1), FILE_DIMENSIONS_2X2, ACTION_UNIT_TECH, (0), (0)) \
    FILE_X(FILE_GRAPHICS_AGE_2_WEST_EUROPE_HOUSE,                             (501), FILE_GRAPHICS_AGE_3_WEST_EUROPE_HOUSE,                   FILE_PRIO_BUILDING, (0), TYPE_HOUSE,                  (0),    (100),    (0),    (0),     (1),  (0),  (0),  (1), FILE_DIMENSIONS_2X2, ACTION_UNIT_TECH, (0), (0)) \
    FILE_X(FILE_GRAPHICS_AGE_3_WEST_EUROPE_HOUSE,                             (502), FILE_GRAPHICS_NONE,                                      FILE_PRIO_BUILDING, (0), TYPE_HOUSE,                  (0),    (100),    (0),    (0),     (1),  (0),  (0),  (1), FILE_DIMENSIONS_2X2, ACTION_UNIT_TECH, (0), (0)) \
    FILE_X(FILE_GRAPHICS_FOREST_TREE_SHADOW,                                  (503), FILE_GRAPHICS_NONE,                                      FILE_PRIO_SHADOW,   (1), TYPE_SHADOW,                 (0),      (0),    (0),    (0),     (1),  (0),  (0),  (1), FILE_DIMENSIONS_1X1, ACTION_NONE,      (1), (0)) \
    FILE_X(FILE_GRAPHICS_BERRY_BUSH,                                          (504), FILE_GRAPHICS_NONE,                                      FILE_PRIO_UNIT,     (0), TYPE_BERRY_BUSH,             (0), (999999),    (0),    (0),     (1),  (0),  (0),  (1), FILE_DIMENSIONS_1X1, ACTION_NONE,      (0), (0)) \
    FILE_X(FILE_GRAPHICS_AGE_1_BARRACKS,                                      (505), FILE_GRAPHICS_AGE_2_WEST_EUROPE_BARRACKS,                FILE_PRIO_BUILDING, (0), TYPE_BARRACKS,               (0),    (100),    (0),    (0),     (1),  (0),  (0),  (1), FILE_DIMENSIONS_3X3, ACTION_UNIT_TECH, (0), (0)) \
    FILE_X(FILE_GRAPHICS_WAYPOINT_FLAG,                                       (506), FILE_GRAPHICS_NONE,                                      FILE_PRIO_UNIT,     (1), TYPE_NONE,                   (0),      (0),    (0),    (0),     (0),  (0),  (0),  (0), FILE_DIMENSIONS_1X1, ACTION_NONE,      (1), (0)) \
    FILE_X(FILE_GRAPHICS_RIGHT_CLICK_RED_ARROWS,                              (507), FILE_GRAPHICS_NONE,                                      FILE_PRIO_UNIT,     (1), TYPE_NONE,                   (0),      (0),    (0),    (0),     (0),  (0),  (1),  (0), FILE_DIMENSIONS_1X1, ACTION_NONE,      (1), (0)) \
    FILE_X(FILE_GRAPHICS_AGE_1_MILL_DONKEY,                                   (508), FILE_GRAPHICS_NONE,                                      FILE_PRIO_BUILDING, (0), TYPE_NONE,                   (0),      (0),    (0),    (0),     (0),  (0),  (0),  (1), FILE_DIMENSIONS_2X2, ACTION_UNIT_TECH, (1), (0)) \
    FILE_X(FILE_GRAPHICS_AGE_1_MILL,                                          (509), FILE_GRAPHICS_NONE,                                      FILE_PRIO_BUILDING, (0), TYPE_MILL,                   (0),    (100),    (0),    (0),     (1),  (0),  (0),  (1), FILE_DIMENSIONS_2X2, ACTION_UNIT_TECH, (0), (0)) \
    FILE_X(FILE_GRAPHICS_WEST_EUROPE_STONE_MINING_CAMP,                       (510), FILE_GRAPHICS_NONE,                                      FILE_PRIO_BUILDING, (0), TYPE_MINING_CAMP,            (0),    (100),    (0),    (0),     (1),  (0),  (0),  (1), FILE_DIMENSIONS_2X2, ACTION_UNIT_TECH, (0), (0)) \
    FILE_X(FILE_GRAPHICS_WEST_EUROPE_LUMBER_CAMP,                             (511), FILE_GRAPHICS_NONE,                                      FILE_PRIO_BUILDING, (0), TYPE_LUMBER_CAMP,            (0),    (100),    (0),    (0),     (1),  (0),  (0),  (1), FILE_DIMENSIONS_2X2, ACTION_UNIT_TECH, (0), (0)) \
    FILE_X(FILE_GRAPHICS_FLAG_TALL,                                           (512), FILE_GRAPHICS_NONE,                                      FILE_PRIO_UNIT,     (0), TYPE_FLAG,                   (0),    (100),    (0),    (0),     (0),  (0),  (0),  (1), FILE_DIMENSIONS_1X1, ACTION_NONE,      (0), (0)) \
    FILE_X(FILE_GRAPHICS_FLAG_MEDIUM,                                         (513), FILE_GRAPHICS_NONE,                                      FILE_PRIO_UNIT,     (0), TYPE_FLAG,                   (0),    (100),    (0),    (0),     (0),  (0),  (0),  (1), FILE_DIMENSIONS_1X1, ACTION_NONE,      (0), (0)) \
    FILE_X(FILE_GRAPHICS_FLAG_SHORT,                                          (514), FILE_GRAPHICS_NONE,                                      FILE_PRIO_UNIT,     (0), TYPE_FLAG,                   (0),    (100),    (0),    (0),     (0),  (0),  (0),  (1), FILE_DIMENSIONS_1X1, ACTION_NONE,      (0), (0)) \
    FILE_X(FILE_GRAPHICS_AGE_1_TOWN_CENTER_ROOF_LEFT,                         (515), FILE_GRAPHICS_NONE,                                      FILE_PRIO_BUILDING, (1), TYPE_TOWN_CENTER,            (0),      (0),    (0),    (0),     (1),  (0),  (0),  (1), FILE_DIMENSIONS_2X1, ACTION_NONE,      (1), (0)) \
    FILE_X(FILE_GRAPHICS_AGE_1_TOWN_CENTER_ROOF_LEFT_SUPPORT_A,               (516), FILE_GRAPHICS_NONE,                                      FILE_PRIO_BUILDING, (1), TYPE_TOWN_CENTER,            (0),      (0),    (0),    (0),     (1),  (0),  (0),  (1), FILE_DIMENSIONS_1X1, ACTION_NONE,      (1), (1)) \
    FILE_X(FILE_GRAPHICS_AGE_1_TOWN_CENTER_ROOF_LEFT_SUPPORT_B,               (517), FILE_GRAPHICS_NONE,                                      FILE_PRIO_BUILDING, (1), TYPE_TOWN_CENTER,            (0),      (0),    (0),    (0),     (1),  (0),  (0),  (1), FILE_DIMENSIONS_1X1, ACTION_NONE,      (1), (0)) \
    FILE_X(FILE_GRAPHICS_AGE_2_WEST_EUROPE_TOWN_CENTER_ROOF_LEFT,             (518), FILE_GRAPHICS_NONE,                                      FILE_PRIO_BUILDING, (1), TYPE_TOWN_CENTER,            (0),      (0),    (0),    (0),     (1),  (0),  (0),  (1), FILE_DIMENSIONS_2X1, ACTION_NONE,      (1), (0)) \
    FILE_X(FILE_GRAPHICS_AGE_2_WEST_EUROPE_TOWN_CENTER_ROOF_LEFT_SUPPORT_A,   (519), FILE_GRAPHICS_NONE,                                      FILE_PRIO_BUILDING, (1), TYPE_TOWN_CENTER,            (0),      (0),    (0),    (0),     (1),  (0),  (0),  (1), FILE_DIMENSIONS_1X1, ACTION_NONE,      (1), (1)) \
    FILE_X(FILE_GRAPHICS_AGE_2_WEST_EUROPE_TOWN_CENTER_ROOF_LEFT_SUPPORT_B,   (520), FILE_GRAPHICS_NONE,                                      FILE_PRIO_BUILDING, (1), TYPE_TOWN_CENTER,            (0),      (0),    (0),    (0),     (1),  (0),  (0),  (1), FILE_DIMENSIONS_1X1, ACTION_NONE,      (1), (0)) \
    FILE_X(FILE_GRAPHICS_AGE_3_WEST_EUROPE_TOWN_CENTER_ROOF_LEFT,             (521), FILE_GRAPHICS_NONE,                                      FILE_PRIO_BUILDING, (1), TYPE_TOWN_CENTER,            (0),      (0),    (0),    (0),     (1),  (0),  (0),  (1), FILE_DIMENSIONS_2X1, ACTION_NONE,      (1), (0)) \
    FILE_X(FILE_GRAPHICS_AGE_3_WEST_EUROPE_TOWN_CENTER_ROOF_LEFT_SUPPORT_A,   (522), FILE_GRAPHICS_NONE,                                      FILE_PRIO_BUILDING, (1), TYPE_TOWN_CENTER,            (0),      (0),    (0),    (0),     (1),  (0),  (0),  (1), FILE_DIMENSIONS_1X1, ACTION_NONE,      (1), (1)) \
    FILE_X(FILE_GRAPHICS_AGE_3_WEST_EUROPE_TOWN_CENTER_ROOF_LEFT_SUPPORT_B,   (523), FILE_GRAPHICS_NONE,                                      FILE_PRIO_BUILDING, (1), TYPE_TOWN_CENTER,            (0),      (0),    (0),    (0),     (1),  (0),  (0),  (1), FILE_DIMENSIONS_1X1, ACTION_NONE,      (1), (0)) \
    FILE_X(FILE_GRAPHICS_OUTPOST,                                             (524), FILE_GRAPHICS_NONE,                                      FILE_PRIO_BUILDING, (0), TYPE_OUTPOST,                (0),    (100),    (0),    (0),     (1),  (0),  (0),  (1), FILE_DIMENSIONS_1X1, ACTION_UNIT_TECH, (0), (0)) \
    FILE_X(FILE_GRAPHICS_OUTPOST_SHADOW,                                      (525), FILE_GRAPHICS_NONE,                                      FILE_PRIO_SHADOW,   (1), TYPE_SHADOW,                 (0),      (0),    (0),    (0),     (1),  (0),  (0),  (1), FILE_DIMENSIONS_1X1, ACTION_NONE,      (1), (0)) \
    FILE_X(FILE_GRAPHICS_GOLD_MINE,                                           (526), FILE_GRAPHICS_NONE,                                      FILE_PRIO_UNIT,     (0), TYPE_GOLD_MINE,              (0), (999999),    (0),    (0),     (1),  (0),  (0),  (1), FILE_DIMENSIONS_1X1, ACTION_NONE,      (0), (0)) \
    FILE_X(FILE_GRAPHICS_AGE_1_TOWN_CENTER_ROOF_RITE,                         (527), FILE_GRAPHICS_NONE,                                      FILE_PRIO_BUILDING, (1), TYPE_TOWN_CENTER,            (0),      (0),    (0),    (0),     (1),  (0),  (0),  (1), FILE_DIMENSIONS_2X1, ACTION_NONE,      (1), (0)) \
    FILE_X(FILE_GRAPHICS_AGE_1_TOWN_CENTER_ROOF_RITE_SUPPORT_A,               (528), FILE_GRAPHICS_NONE,                                      FILE_PRIO_BUILDING, (1), TYPE_TOWN_CENTER,            (0),      (0),    (0),    (0),     (1),  (0),  (0),  (1), FILE_DIMENSIONS_1X1, ACTION_NONE,      (1), (1)) \
    FILE_X(FILE_GRAPHICS_AGE_1_TOWN_CENTER_ROOF_RITE_SUPPORT_B,               (529), FILE_GRAPHICS_NONE,                                      FILE_PRIO_BUILDING, (1), TYPE_TOWN_CENTER,            (0),      (0),    (0),    (0),     (1),  (0),  (0),  (1), FILE_DIMENSIONS_1X1, ACTION_NONE,      (1), (0)) \
    FILE_X(FILE_GRAPHICS_AGE_2_WEST_EUROPE_TOWN_CENTER_ROOF_RITE,             (530), FILE_GRAPHICS_NONE,                                      FILE_PRIO_BUILDING, (1), TYPE_TOWN_CENTER,            (0),      (0),    (0),    (0),     (1),  (0),  (0),  (1), FILE_DIMENSIONS_2X1, ACTION_NONE,      (1), (0)) \
    FILE_X(FILE_GRAPHICS_AGE_2_WEST_EUROPE_TOWN_CENTER_ROOF_RITE_SUPPORT_A,   (531), FILE_GRAPHICS_NONE,                                      FILE_PRIO_BUILDING, (1), TYPE_TOWN_CENTER,            (0),      (0),    (0),    (0),     (1),  (0),  (0),  (1), FILE_DIMENSIONS_1X1, ACTION_NONE,      (1), (1)) \
    FILE_X(FILE_GRAPHICS_AGE_2_WEST_EUROPE_TOWN_CENTER_ROOF_RITE_SUPPORT_B,   (532), FILE_GRAPHICS_NONE,                                      FILE_PRIO_BUILDING, (1), TYPE_TOWN_CENTER,            (0),      (0),    (0),    (0),     (1),  (0),  (0),  (1), FILE_DIMENSIONS_1X1, ACTION_NONE,      (1), (0)) \
    FILE_X(FILE_GRAPHICS_AGE_3_WEST_EUROPE_TOWN_CENTER_ROOF_RITE,             (533), FILE_GRAPHICS_NONE,                                      FILE_PRIO_BUILDING, (1), TYPE_TOWN_CENTER,            (0),      (0),    (0),    (0),     (1),  (0),  (0),  (1), FILE_DIMENSIONS_2X1, ACTION_NONE,      (1), (0)) \
    FILE_X(FILE_GRAPHICS_AGE_3_WEST_EUROPE_TOWN_CENTER_ROOF_RITE_SUPPORT_A,   (534), FILE_GRAPHICS_NONE,                                      FILE_PRIO_BUILDING, (1), TYPE_TOWN_CENTER,            (0),      (0),    (0),    (0),     (1),  (0),  (0),  (1), FILE_DIMENSIONS_1X1, ACTION_NONE,      (1), (1)) \
    FILE_X(FILE_GRAPHICS_AGE_3_WEST_EUROPE_TOWN_CENTER_ROOF_RITE_SUPPORT_B,   (535), FILE_GRAPHICS_NONE,                                      FILE_PRIO_BUILDING, (1), TYPE_TOWN_CENTER,            (0),      (0),    (0),    (0),     (1),  (0),  (0),  (1), FILE_DIMENSIONS_1X1, ACTION_NONE,      (1), (0)) \
    FILE_X(FILE_GRAPHICS_FOREST_TREE,                                         (536), FILE_GRAPHICS_NONE,                                      FILE_PRIO_BUILDING, (0), TYPE_TREE,                   (0), (999999),    (0),    (0),     (1),  (0),  (0),  (1), FILE_DIMENSIONS_1X1, ACTION_NONE,      (0), (0))
