#pragma once

typedef enum
{
    ICON_BUILD_BARRACKS = 2,
    ICON_BUILD_MILL = 19,
    ICON_BUILD_PALISADE_WALL,
    ICON_BUILD_HOUSE = 34,
    ICON_BUILD_OUTPOST,
    ICON_BUILD_STONE_CAMP,
    ICON_BUILD_LUMBER_CAMP,

    ICON_UNIT_MILITIA = 8,
    ICON_UNIT_VILLAGER = 15,
}
Icon;
