#pragma once

typedef enum
{
    ICON_BUILD_ARCHERY_RANGE = 0,
    ICON_BUILD_BARRACKS,
    ICON_BUILD_BLACKSMITH,
    ICON_BUILD_CASTLE,
    ICON_BUILD_OUTPOST,
    ICON_BUILD_MONASTARY,
    ICON_BUILD_DOCK,
    ICON_BUILD_MARKET,
    ICON_BUILD_MILL,
    ICON_BUILD_SIEGE_WORKSHOP,
    ICON_BUILD_STABLE,
    ICON_BUILD_WATCH_TOWER,
    ICON_BUILD_TOWN_CENTER,
    ICON_BUILD_STONE_WALL,
    ICON_BUILD_PALISADE_WALL,
    ICON_BUILD_FORITIFIED_WALL,
    ICON_BUILD_UNI,
    ICON_BUILD_HOUSE,
    ICON_BUILD_FARM,
    ICON_BUILD_GATE,
    ICON_BUILD_WONDER,
    ICON_BUILD_OUTPOST,
    ICON_BUILD_STONE_CAMP,
    ICON_BUILD_LUMBER_CAMP,
    ICON_BUILD_FISHING_TRAP,
    ICON_BUILD_BOMBARD_TOWER,
    ICON_BUILD_YURT,
}
Icon;
