#pragma once

typedef enum
{
    TRIGGER_NONE,
    TRIGGER_AGE_UP_2,
    TRIGGER_AGE_UP_3,
    TRIGGER_AGE_UP_4,
    TRIGGER_UPGRADE_MILITIA,
    TRIGGER_UPGRADE_MAN_AT_ARMS,
    TRIGGER_UPGRADE_LONG_SWORDSMAN,
}
Trigger;
