#pragma once

typedef enum
{
    TYPE_NONE = -1,
    TYPE_VILLAGER,
    TYPE_TEUTONIC_KNIGHT,
    TYPE_SHADOW,
    TYPE_BERRY_BUSH,
    TYPE_KNIGHT,
    TYPE_GOLD_MINE,
    TYPE_STONE_MINE,
    TYPE_TREE_CHOPPED_DOWN,
    TYPE_BARRACKS,
    TYPE_WONDER,
    TYPE_HOUSE,
    TYPE_RUBBLE,
    TYPE_TREE,
}
Type;
