#pragma once

typedef enum
{
    TYPE_NONE = -1,
    TYPE_VILLAGER,
    TYPE_TEUTONIC_KNIGHT,
    TYPE_FIRE,
    TYPE_SHADOW,
    TYPE_TOWN_CENTER,
    TYPE_BERRY_BUSH,
    TYPE_KNIGHT,
    TYPE_GOLD_MINE,
    TYPE_STONE_MINE,
    TYPE_CASTLE,
    TYPE_BARRACKS,
    TYPE_WONDER,
    TYPE_HOUSE,
    TYPE_RUBBLE,
    TYPE_TREE,
    // Resources.
    TYPE_FOOD,
    TYPE_WOOD,
    TYPE_GOLD,
    TYPE_STONE,
}
Type;
